// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ go get github.com/boundaryml/baml
//
// ----------------------------------------------------------------------------

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ go install github.com/boundaryml/baml/baml-cli

package baml_client

import (
	"context"
	"fmt"

	baml "github.com/boundaryml/baml/engine/language_client_go/pkg"
	"github.com/meroxa/prod/cli/baml_client/stream_types"
)

type parse_stream struct{}

var ParseStream = &parse_stream{}

// / Parse version of CategorizeRoutes (Takes in string and returns stream_types.CategorizedRoutes)
func (*parse_stream) CategorizeRoutes(text string, opts ...CallOptionFunc) (stream_types.CategorizedRoutes, error) {
	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"text": text, "stream": true},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		// This should never happen. if it does, please file an issue at https://github.com/boundaryml/baml/issues
		// and include the type of the args you're passing in.
		wrapped_err := fmt.Errorf("BAML INTERNAL ERROR: CategorizeRoutes: %w", err)
		panic(wrapped_err)
	}

	result, err := bamlRuntime.CallFunctionParse(context.Background(), "CategorizeRoutes", encoded)
	if err != nil {
		return stream_types.CategorizedRoutes{}, err
	}

	casted := (result).(stream_types.CategorizedRoutes)

	return casted, nil
}

// / Parse version of DetermineBuildOutput (Takes in string and returns stream_types.BuildOutput)
func (*parse_stream) DetermineBuildOutput(text string, opts ...CallOptionFunc) (stream_types.BuildOutput, error) {
	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"text": text, "stream": true},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		// This should never happen. if it does, please file an issue at https://github.com/boundaryml/baml/issues
		// and include the type of the args you're passing in.
		wrapped_err := fmt.Errorf("BAML INTERNAL ERROR: DetermineBuildOutput: %w", err)
		panic(wrapped_err)
	}

	result, err := bamlRuntime.CallFunctionParse(context.Background(), "DetermineBuildOutput", encoded)
	if err != nil {
		return stream_types.BuildOutput{}, err
	}

	casted := (result).(stream_types.BuildOutput)

	return casted, nil
}

// / Parse version of DetermineEnvVarRoles (Takes in string and returns stream_types.EnvVarCategory)
func (*parse_stream) DetermineEnvVarRoles(text string, opts ...CallOptionFunc) (stream_types.EnvVarCategory, error) {
	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"text": text, "stream": true},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		// This should never happen. if it does, please file an issue at https://github.com/boundaryml/baml/issues
		// and include the type of the args you're passing in.
		wrapped_err := fmt.Errorf("BAML INTERNAL ERROR: DetermineEnvVarRoles: %w", err)
		panic(wrapped_err)
	}

	result, err := bamlRuntime.CallFunctionParse(context.Background(), "DetermineEnvVarRoles", encoded)
	if err != nil {
		return stream_types.EnvVarCategory{}, err
	}

	casted := (result).(stream_types.EnvVarCategory)

	return casted, nil
}

// / Parse version of DetermineLaunchCommand (Takes in string and returns stream_types.LaunchCommand)
func (*parse_stream) DetermineLaunchCommand(text string, opts ...CallOptionFunc) (stream_types.LaunchCommand, error) {
	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"text": text, "stream": true},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		// This should never happen. if it does, please file an issue at https://github.com/boundaryml/baml/issues
		// and include the type of the args you're passing in.
		wrapped_err := fmt.Errorf("BAML INTERNAL ERROR: DetermineLaunchCommand: %w", err)
		panic(wrapped_err)
	}

	result, err := bamlRuntime.CallFunctionParse(context.Background(), "DetermineLaunchCommand", encoded)
	if err != nil {
		return stream_types.LaunchCommand{}, err
	}

	casted := (result).(stream_types.LaunchCommand)

	return casted, nil
}

// / Parse version of DetermineMigrationCommand (Takes in string and returns stream_types.MigrationCommand)
func (*parse_stream) DetermineMigrationCommand(text string, opts ...CallOptionFunc) (stream_types.MigrationCommand, error) {
	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"text": text, "stream": true},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		// This should never happen. if it does, please file an issue at https://github.com/boundaryml/baml/issues
		// and include the type of the args you're passing in.
		wrapped_err := fmt.Errorf("BAML INTERNAL ERROR: DetermineMigrationCommand: %w", err)
		panic(wrapped_err)
	}

	result, err := bamlRuntime.CallFunctionParse(context.Background(), "DetermineMigrationCommand", encoded)
	if err != nil {
		return stream_types.MigrationCommand{}, err
	}

	casted := (result).(stream_types.MigrationCommand)

	return casted, nil
}

// / Parse version of ExtractIntent (Takes in string and returns stream_types.Intent)
func (*parse_stream) ExtractIntent(text string, opts ...CallOptionFunc) (stream_types.Intent, error) {
	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"text": text, "stream": true},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		// This should never happen. if it does, please file an issue at https://github.com/boundaryml/baml/issues
		// and include the type of the args you're passing in.
		wrapped_err := fmt.Errorf("BAML INTERNAL ERROR: ExtractIntent: %w", err)
		panic(wrapped_err)
	}

	result, err := bamlRuntime.CallFunctionParse(context.Background(), "ExtractIntent", encoded)
	if err != nil {
		return stream_types.Intent{}, err
	}

	casted := (result).(stream_types.Intent)

	return casted, nil
}

// / Parse version of FetchPricing (Takes in string and returns stream_types.ServicePricing)
func (*parse_stream) FetchPricing(text string, opts ...CallOptionFunc) (stream_types.ServicePricing, error) {
	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"text": text, "stream": true},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		// This should never happen. if it does, please file an issue at https://github.com/boundaryml/baml/issues
		// and include the type of the args you're passing in.
		wrapped_err := fmt.Errorf("BAML INTERNAL ERROR: FetchPricing: %w", err)
		panic(wrapped_err)
	}

	result, err := bamlRuntime.CallFunctionParse(context.Background(), "FetchPricing", encoded)
	if err != nil {
		return stream_types.ServicePricing{}, err
	}

	casted := (result).(stream_types.ServicePricing)

	return casted, nil
}

// / Parse version of SummarizeDeployError (Takes in string and returns stream_types.Error)
func (*parse_stream) SummarizeDeployError(text string, opts ...CallOptionFunc) (stream_types.Error, error) {
	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"text": text, "stream": true},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		// This should never happen. if it does, please file an issue at https://github.com/boundaryml/baml/issues
		// and include the type of the args you're passing in.
		wrapped_err := fmt.Errorf("BAML INTERNAL ERROR: SummarizeDeployError: %w", err)
		panic(wrapped_err)
	}

	result, err := bamlRuntime.CallFunctionParse(context.Background(), "SummarizeDeployError", encoded)
	if err != nil {
		return stream_types.Error{}, err
	}

	casted := (result).(stream_types.Error)

	return casted, nil
}

// / Parse version of SummarizeIntent (Takes in string and returns stream_types.Summary)
func (*parse_stream) SummarizeIntent(text string, opts ...CallOptionFunc) (stream_types.Summary, error) {
	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"text": text, "stream": true},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		// This should never happen. if it does, please file an issue at https://github.com/boundaryml/baml/issues
		// and include the type of the args you're passing in.
		wrapped_err := fmt.Errorf("BAML INTERNAL ERROR: SummarizeIntent: %w", err)
		panic(wrapped_err)
	}

	result, err := bamlRuntime.CallFunctionParse(context.Background(), "SummarizeIntent", encoded)
	if err != nil {
		return stream_types.Summary{}, err
	}

	casted := (result).(stream_types.Summary)

	return casted, nil
}

// / Parse version of SummarizeSteps (Takes in string and returns stream_types.Summary)
func (*parse_stream) SummarizeSteps(text string, opts ...CallOptionFunc) (stream_types.Summary, error) {
	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"text": text, "stream": true},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		// This should never happen. if it does, please file an issue at https://github.com/boundaryml/baml/issues
		// and include the type of the args you're passing in.
		wrapped_err := fmt.Errorf("BAML INTERNAL ERROR: SummarizeSteps: %w", err)
		panic(wrapped_err)
	}

	result, err := bamlRuntime.CallFunctionParse(context.Background(), "SummarizeSteps", encoded)
	if err != nil {
		return stream_types.Summary{}, err
	}

	casted := (result).(stream_types.Summary)

	return casted, nil
}
