// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ go get github.com/boundaryml/baml
//
// ----------------------------------------------------------------------------

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ go install github.com/boundaryml/baml/baml-cli

package baml_client

import (
	"context"
	"fmt"

	baml "github.com/boundaryml/baml/engine/language_client_go/pkg"
	"github.com/meroxa/prod/cli/baml_client/stream_types"
	"github.com/meroxa/prod/cli/baml_client/types"
)

type stream struct{}

var Stream = &stream{}

type StreamValue[TStream any, TFinal any] struct {
	IsFinal   bool
	as_final  *TFinal
	as_stream *TStream
}

func (s *StreamValue[TStream, TFinal]) Final() TFinal {
	return *s.as_final
}

func (s *StreamValue[TStream, TFinal]) Stream() TStream {
	return *s.as_stream
}

// / Streaming version of ExtractIntent
func (*stream) ExtractIntent(ctx context.Context, request string, opts ...CallOptionFunc) (<-chan StreamValue[stream_types.Intent, types.Intent], error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"request": request},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	encoded, err := baml.EncodeArgs(args)
	if err != nil {
		// This should never happen. if it does, please file an issue at https://github.com/boundaryml/baml/issues
		// and include the type of the args you're passing in.
		wrapped_err := fmt.Errorf("BAML INTERNAL ERROR: ExtractIntent: %w", err)
		panic(wrapped_err)
	}

	internal_ctx := context.Background()
	internal_channel, err := bamlRuntime.CallFunctionStream(internal_ctx, "ExtractIntent", encoded)
	if err != nil {
		return nil, err
	}

	channel := make(chan StreamValue[stream_types.Intent, types.Intent])
	go func() {
		defer func() {
			internal_ctx.Done()
		}()
		for {
			select {
			case <-ctx.Done():
				close(channel)
				return
			case result, ok := <-internal_channel:
				if !ok {
					close(channel)
					return
				}
				if result.Error != nil {
					close(channel)
					return
				}
				if result.HasData {
					data := *(result.Data).(*types.Intent)
					channel <- StreamValue[stream_types.Intent, types.Intent]{
						IsFinal:  true,
						as_final: &data,
					}
				} else {
					data := *(result.StreamData).(*stream_types.Intent)
					channel <- StreamValue[stream_types.Intent, types.Intent]{
						IsFinal:   false,
						as_stream: &data,
					}
				}
			}
		}
	}()
	return channel, nil
}
