// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ go get github.com/boundaryml/baml
//
// ----------------------------------------------------------------------------

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ go install github.com/boundaryml/baml/baml-cli

package baml_client

import (
	"context"

	baml "github.com/boundaryml/baml/engine/language_client_go/pkg"
	"github.com/meroxa/prod/cli/baml_client/types"
)

func CategorizeRoutes(ctx context.Context, candidates []types.RouteCandidate, opts ...CallOptionFunc) (types.CategorizedRoutes, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"candidates": candidates},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	encoded, err := baml.EncodeArgs(args)
	if err != nil {
		panic(err)
	}

	result, err := bamlRuntime.CallFunction(ctx, "CategorizeRoutes", encoded)
	if err != nil {
		return types.CategorizedRoutes{}, err
	}

	if result.Error != nil {
		return types.CategorizedRoutes{}, result.Error
	}

	casted := *(result.Data).(*types.CategorizedRoutes)

	return casted, nil
}

func DetermineBuildOutput(ctx context.Context, candidate types.BuildOutputCandidate, opts ...CallOptionFunc) (types.BuildOutput, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"candidate": candidate},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	encoded, err := baml.EncodeArgs(args)
	if err != nil {
		panic(err)
	}

	result, err := bamlRuntime.CallFunction(ctx, "DetermineBuildOutput", encoded)
	if err != nil {
		return types.BuildOutput{}, err
	}

	if result.Error != nil {
		return types.BuildOutput{}, result.Error
	}

	casted := *(result.Data).(*types.BuildOutput)

	return casted, nil
}

func DetermineEnvVarRoles(ctx context.Context, envVar types.EnvVarCandidate, dbList []string, opts ...CallOptionFunc) (types.EnvVarCategory, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"envVar": envVar, "dbList": dbList},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	encoded, err := baml.EncodeArgs(args)
	if err != nil {
		panic(err)
	}

	result, err := bamlRuntime.CallFunction(ctx, "DetermineEnvVarRoles", encoded)
	if err != nil {
		return types.EnvVarCategory{}, err
	}

	if result.Error != nil {
		return types.EnvVarCategory{}, result.Error
	}

	casted := *(result.Data).(*types.EnvVarCategory)

	return casted, nil
}

func DetermineLaunchCommand(ctx context.Context, language string, frameworks []string, envVars []string, lc types.LaunchContext, opts ...CallOptionFunc) (types.LaunchCommand, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"language": language, "frameworks": frameworks, "envVars": envVars, "lc": lc},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	encoded, err := baml.EncodeArgs(args)
	if err != nil {
		panic(err)
	}

	result, err := bamlRuntime.CallFunction(ctx, "DetermineLaunchCommand", encoded)
	if err != nil {
		return types.LaunchCommand{}, err
	}

	if result.Error != nil {
		return types.LaunchCommand{}, result.Error
	}

	casted := *(result.Data).(*types.LaunchCommand)

	return casted, nil
}

func ExtractIntent(ctx context.Context, request string, opts ...CallOptionFunc) (types.Intent, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"request": request},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	encoded, err := baml.EncodeArgs(args)
	if err != nil {
		panic(err)
	}

	result, err := bamlRuntime.CallFunction(ctx, "ExtractIntent", encoded)
	if err != nil {
		return types.Intent{}, err
	}

	if result.Error != nil {
		return types.Intent{}, result.Error
	}

	casted := *(result.Data).(*types.Intent)

	return casted, nil
}

func FetchPricing(ctx context.Context, service types.Service, content string, opts ...CallOptionFunc) (types.ServicePricing, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"service": service, "content": content},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	encoded, err := baml.EncodeArgs(args)
	if err != nil {
		panic(err)
	}

	result, err := bamlRuntime.CallFunction(ctx, "FetchPricing", encoded)
	if err != nil {
		return types.ServicePricing{}, err
	}

	if result.Error != nil {
		return types.ServicePricing{}, result.Error
	}

	casted := *(result.Data).(*types.ServicePricing)

	return casted, nil
}

func SummarizeDeployError(ctx context.Context, errorMsg string, intent types.Intent, spec types.ProjectSpec, os string, violations []string, opts ...CallOptionFunc) (types.Error, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"errorMsg": errorMsg, "intent": intent, "spec": spec, "os": os, "violations": violations},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	encoded, err := baml.EncodeArgs(args)
	if err != nil {
		panic(err)
	}

	result, err := bamlRuntime.CallFunction(ctx, "SummarizeDeployError", encoded)
	if err != nil {
		return types.Error{}, err
	}

	if result.Error != nil {
		return types.Error{}, result.Error
	}

	casted := *(result.Data).(*types.Error)

	return casted, nil
}

func SummarizeIntent(ctx context.Context, intent types.Intent, name string, language string, opts ...CallOptionFunc) (types.Summary, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"intent": intent, "name": name, "language": language},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	encoded, err := baml.EncodeArgs(args)
	if err != nil {
		panic(err)
	}

	result, err := bamlRuntime.CallFunction(ctx, "SummarizeIntent", encoded)
	if err != nil {
		return types.Summary{}, err
	}

	if result.Error != nil {
		return types.Summary{}, result.Error
	}

	casted := *(result.Data).(*types.Summary)

	return casted, nil
}

func SummarizeSteps(ctx context.Context, steps []string, opts ...CallOptionFunc) (types.Summary, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"steps": steps},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	encoded, err := baml.EncodeArgs(args)
	if err != nil {
		panic(err)
	}

	result, err := bamlRuntime.CallFunction(ctx, "SummarizeSteps", encoded)
	if err != nil {
		return types.Summary{}, err
	}

	if result.Error != nil {
		return types.Summary{}, result.Error
	}

	casted := *(result.Data).(*types.Summary)

	return casted, nil
}
