// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ go get github.com/boundaryml/baml
//
// ----------------------------------------------------------------------------

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ go install github.com/boundaryml/baml/baml-cli

package baml_client

import (
	"context"

	baml "github.com/boundaryml/baml/engine/language_client_go/pkg"
	"github.com/meroxa/prod/cli/baml_client/types"
)

func ExtractIntent(ctx context.Context, request string, opts ...CallOptionFunc) (types.Intent, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"request": request},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	encoded, err := baml.EncodeArgs(args)
	if err != nil {
		panic(err)
	}

	result, err := bamlRuntime.CallFunction(ctx, "ExtractIntent", encoded)
	if err != nil {
		return types.Intent{}, err
	}

	if result.Error != nil {
		return types.Intent{}, result.Error
	}

	casted := *(result.Data).(*types.Intent)

	return casted, nil
}
