// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ go get github.com/boundaryml/baml
//
// ----------------------------------------------------------------------------

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ go install github.com/boundaryml/baml/baml-cli

package baml_client

import (
	"reflect"

	"github.com/meroxa/prod/cli/baml_client/stream_types"
	"github.com/meroxa/prod/cli/baml_client/types"
)

var typeMap = map[string]reflect.Type{
	"TYPES.Intent":                 reflect.TypeOf(types.Intent{}),
	"STREAM_TYPES.Intent":          reflect.TypeOf(stream_types.Intent{}),
	"TYPES.PricingResponse":        reflect.TypeOf(types.PricingResponse{}),
	"STREAM_TYPES.PricingResponse": reflect.TypeOf(stream_types.PricingResponse{}),
	"TYPES.ServicePricing":         reflect.TypeOf(types.ServicePricing{}),
	"STREAM_TYPES.ServicePricing":  reflect.TypeOf(stream_types.ServicePricing{}),
	"TYPES.Summary":                reflect.TypeOf(types.Summary{}),
	"STREAM_TYPES.Summary":         reflect.TypeOf(stream_types.Summary{}),
}
