// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ go get github.com/boundaryml/baml
//
// ----------------------------------------------------------------------------

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ go install github.com/boundaryml/baml/baml-cli

package baml_client

import (
	"reflect"

	"github.com/meroxa/prod/cli/baml_client/stream_types"
	"github.com/meroxa/prod/cli/baml_client/types"
)

var typeMap = map[string]reflect.Type{
	"TYPES.EnvVarCandidate":           reflect.TypeOf(types.EnvVarCandidate{}),
	"STREAM_TYPES.EnvVarCandidate":    reflect.TypeOf(stream_types.EnvVarCandidate{}),
	"TYPES.EnvVarCategory":            reflect.TypeOf(types.EnvVarCategory{}),
	"STREAM_TYPES.EnvVarCategory":     reflect.TypeOf(stream_types.EnvVarCategory{}),
	"TYPES.Error":                     reflect.TypeOf(types.Error{}),
	"STREAM_TYPES.Error":              reflect.TypeOf(stream_types.Error{}),
	"TYPES.Intent":                    reflect.TypeOf(types.Intent{}),
	"STREAM_TYPES.Intent":             reflect.TypeOf(stream_types.Intent{}),
	"TYPES.PricingResponse":           reflect.TypeOf(types.PricingResponse{}),
	"STREAM_TYPES.PricingResponse":    reflect.TypeOf(stream_types.PricingResponse{}),
	"TYPES.ProjectSpec":               reflect.TypeOf(types.ProjectSpec{}),
	"STREAM_TYPES.ProjectSpec":        reflect.TypeOf(stream_types.ProjectSpec{}),
	"TYPES.Remediation":               reflect.TypeOf(types.Remediation{}),
	"STREAM_TYPES.Remediation":        reflect.TypeOf(stream_types.Remediation{}),
	"TYPES.ServicePricing":            reflect.TypeOf(types.ServicePricing{}),
	"STREAM_TYPES.ServicePricing":     reflect.TypeOf(stream_types.ServicePricing{}),
	"TYPES.ServiceRequirement":        reflect.TypeOf(types.ServiceRequirement{}),
	"STREAM_TYPES.ServiceRequirement": reflect.TypeOf(stream_types.ServiceRequirement{}),
	"TYPES.Summary":                   reflect.TypeOf(types.Summary{}),
	"STREAM_TYPES.Summary":            reflect.TypeOf(stream_types.Summary{}),
}
