-- This file contains seed data for your local Supabase instance
-- You can add initial data, test users, or any other setup data here

-- Example: Create a test user
-- INSERT INTO auth.users (
--   id,
--   email,
--   encrypted_password,
--   email_confirmed_at,
--   created_at,
--   updated_at
-- ) VALUES (
--   '00000000-0000-0000-0000-000000000000',
--   'test@example.com',
--   crypt('password', gen_salt('bf')),
--   now(),
--   now(),
--   now()
-- );

-- Example: Create some initial data for your application
-- INSERT INTO public.your_table (id, name, created_at) VALUES
--   (1, 'Example Item 1', now()),
--   (2, 'Example Item 2', now()); 