// Code generated by "stringer -type=Platform,Action -output=types_string.go"; DO NOT EDIT.

package agent

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Render-0]
	_ = x[FlyIO-1]
	_ = x[Netlify-2]
	_ = x[Vercel-3]
	_ = x[UnknownPlatform-4]
}

const _Platform_name = "RenderFlyIONetlifyVercelUnknownPlatform"

var _Platform_index = [...]uint8{0, 6, 11, 18, 24, 39}

func (i Platform) String() string {
	if i < 0 || i >= Platform(len(_Platform_index)-1) {
		return "Platform(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Platform_name[_Platform_index[i]:_Platform_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Deploy-0]
	_ = x[UnknownAction-1]
}

const _Action_name = "DeployUnknownAction"

var _Action_index = [...]uint8{0, 6, 19}

func (i Action) String() string {
	if i < 0 || i >= Action(len(_Action_index)-1) {
		return "Action(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Action_name[_Action_index[i]:_Action_index[i+1]]
}
