// Code generated by "stringer -type=Platform,Action -output=types_string.go"; DO NOT EDIT.

package agent

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[pluginPlatformBase-1048576]
	_ = x[Render-0]
	_ = x[FlyIO-1]
	_ = x[Netlify-2]
	_ = x[Vercel-3]
	_ = x[Heroku-4]
	_ = x[AWS-5]
	_ = x[GoogleCloudRun-6]
	_ = x[Azure-7]
	_ = x[UnknownPlatform-8]
	_ = x[Modal-9]
}

const (
	_Platform_name_0 = "RenderFlyIONetlifyVercelHerokuAWSGoogleCloudRunAzureUnknownPlatformModal"
	_Platform_name_1 = "pluginPlatformBase"
)

var (
	_Platform_index_0 = [...]uint8{0, 6, 11, 18, 24, 30, 33, 47, 52, 67, 72}
)

func (i Platform) String() string {
	switch {
	case 0 <= i && i <= 9:
		return _Platform_name_0[_Platform_index_0[i]:_Platform_index_0[i+1]]
	case i == 1048576:
		return _Platform_name_1
	default:
		return "Platform(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Deploy-0]
	_ = x[Rollback-1]
	_ = x[UnknownAction-2]
	_ = x[Destroy-3]
}

const _Action_name = "DeployRollbackUnknownActionDestroy"

var _Action_index = [...]uint8{0, 6, 14, 27, 34}

func (i Action) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Action_index)-1 {
		return "Action(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Action_name[_Action_index[idx]:_Action_index[idx+1]]
}
