// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ go get github.com/boundaryml/baml
//
// ----------------------------------------------------------------------------

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ go install github.com/boundaryml/baml/baml-cli

package stream_types

import (
	"fmt"

	baml "github.com/boundaryml/baml/engine/language_client_go/pkg"
	"github.com/boundaryml/baml/engine/language_client_go/pkg/cffi"
)

type Intent struct {
	Action   *string `json:"action"`
	Platform *string `json:"platform"`
	Source   *string `json:"source"`
}

func (c *Intent) Decode(holder *cffi.CFFIValueClass) {
	typeName := holder.Name
	if typeName.Namespace != cffi.CFFITypeNamespace_STREAM_TYPES {
		panic(fmt.Sprintf("expected cffi.CFFITypeNamespace_STREAM_TYPES, got %s", string(typeName.Namespace.String())))
	}
	if typeName.Name != "Intent" {
		panic(fmt.Sprintf("expected Intent, got %s", typeName.Name))
	}

	for _, field := range holder.Fields {
		key := field.Key
		valueHolder := field.Value
		switch key {

		case "action":
			c.Action = func(param *cffi.CFFIValueHolder) *string {
				decoded := baml.Decode(param)
				return func(result any) *string {
					if result == nil {
						return nil
					}
					casted := (result).(string)
					return &casted
				}(decoded)
			}(valueHolder)

		case "platform":
			c.Platform = func(param *cffi.CFFIValueHolder) *string {
				decoded := baml.Decode(param)
				return func(result any) *string {
					if result == nil {
						return nil
					}
					casted := (result).(string)
					return &casted
				}(decoded)
			}(valueHolder)

		case "source":
			c.Source = func(param *cffi.CFFIValueHolder) *string {
				decoded := baml.Decode(param)
				return func(result any) *string {
					if result == nil {
						return nil
					}
					casted := (result).(string)
					return &casted
				}(decoded)
			}(valueHolder)

		default:
			panic(fmt.Sprintf("unexpected field: %s", key))
		}
	}

}

func (c Intent) Encode() (*cffi.CFFIValueHolder, error) {
	fields := map[string]any{}

	fields["action"] = c.Action

	fields["platform"] = c.Platform

	fields["source"] = c.Source

	return baml.EncodeClass(c.BamlEncodeName, fields, nil)
}

func (c Intent) BamlTypeName() string {
	return "Intent"
}

func (u Intent) BamlEncodeName() *cffi.CFFITypeName {
	return &cffi.CFFITypeName{
		Namespace: cffi.CFFITypeNamespace_STREAM_TYPES,
		Name:      "Intent",
	}
}

type Summary struct {
	Summary *string `json:"summary"`
}

func (c *Summary) Decode(holder *cffi.CFFIValueClass) {
	typeName := holder.Name
	if typeName.Namespace != cffi.CFFITypeNamespace_STREAM_TYPES {
		panic(fmt.Sprintf("expected cffi.CFFITypeNamespace_STREAM_TYPES, got %s", string(typeName.Namespace.String())))
	}
	if typeName.Name != "Summary" {
		panic(fmt.Sprintf("expected Summary, got %s", typeName.Name))
	}

	for _, field := range holder.Fields {
		key := field.Key
		valueHolder := field.Value
		switch key {

		case "summary":
			c.Summary = func(param *cffi.CFFIValueHolder) *string {
				decoded := baml.Decode(param)
				return func(result any) *string {
					if result == nil {
						return nil
					}
					casted := (result).(string)
					return &casted
				}(decoded)
			}(valueHolder)

		default:
			panic(fmt.Sprintf("unexpected field: %s", key))
		}
	}

}

func (c Summary) Encode() (*cffi.CFFIValueHolder, error) {
	fields := map[string]any{}

	fields["summary"] = c.Summary

	return baml.EncodeClass(c.BamlEncodeName, fields, nil)
}

func (c Summary) BamlTypeName() string {
	return "Summary"
}

func (u Summary) BamlEncodeName() *cffi.CFFITypeName {
	return &cffi.CFFITypeName{
		Namespace: cffi.CFFITypeNamespace_STREAM_TYPES,
		Name:      "Summary",
	}
}
