// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ go get github.com/boundaryml/baml
//
// ----------------------------------------------------------------------------

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ go install github.com/boundaryml/baml/baml-cli

package stream_types

import (
	"fmt"

	baml "github.com/boundaryml/baml/engine/language_client_go/pkg"
	"github.com/boundaryml/baml/engine/language_client_go/pkg/cffi"
)

type BuildOutput struct {
	Path *string `json:"path"`
}

func (c *BuildOutput) Decode(holder *cffi.CFFIValueClass) {
	typeName := holder.Name
	if typeName.Namespace != cffi.CFFITypeNamespace_STREAM_TYPES {
		panic(fmt.Sprintf("expected cffi.CFFITypeNamespace_STREAM_TYPES, got %s", string(typeName.Namespace.String())))
	}
	if typeName.Name != "BuildOutput" {
		panic(fmt.Sprintf("expected BuildOutput, got %s", typeName.Name))
	}

	for _, field := range holder.Fields {
		key := field.Key
		valueHolder := field.Value
		switch key {

		case "path":
			c.Path = func(param *cffi.CFFIValueHolder) *string {
				decoded := baml.Decode(param)
				return func(result any) *string {
					if result == nil {
						return nil
					}
					casted := (result).(string)
					return &casted
				}(decoded)
			}(valueHolder)

		default:
			panic(fmt.Sprintf("unexpected field: %s", key))
		}
	}

}

func (c BuildOutput) Encode() (*cffi.CFFIValueHolder, error) {
	fields := map[string]any{}

	fields["path"] = c.Path

	return baml.EncodeClass(c.BamlEncodeName, fields, nil)
}

func (c BuildOutput) BamlTypeName() string {
	return "BuildOutput"
}

func (u BuildOutput) BamlEncodeName() *cffi.CFFITypeName {
	return &cffi.CFFITypeName{
		Namespace: cffi.CFFITypeNamespace_STREAM_TYPES,
		Name:      "BuildOutput",
	}
}

type BuildOutputCandidate struct {
	Default   *string `json:"default"`
	Source    *string `json:"source"`
	Framework *string `json:"framework"`
	Context   *string `json:"context"`
}

func (c *BuildOutputCandidate) Decode(holder *cffi.CFFIValueClass) {
	typeName := holder.Name
	if typeName.Namespace != cffi.CFFITypeNamespace_STREAM_TYPES {
		panic(fmt.Sprintf("expected cffi.CFFITypeNamespace_STREAM_TYPES, got %s", string(typeName.Namespace.String())))
	}
	if typeName.Name != "BuildOutputCandidate" {
		panic(fmt.Sprintf("expected BuildOutputCandidate, got %s", typeName.Name))
	}

	for _, field := range holder.Fields {
		key := field.Key
		valueHolder := field.Value
		switch key {

		case "default":
			c.Default = func(param *cffi.CFFIValueHolder) *string {
				decoded := baml.Decode(param)
				return func(result any) *string {
					if result == nil {
						return nil
					}
					casted := (result).(string)
					return &casted
				}(decoded)
			}(valueHolder)

		case "source":
			c.Source = func(param *cffi.CFFIValueHolder) *string {
				decoded := baml.Decode(param)
				return func(result any) *string {
					if result == nil {
						return nil
					}
					casted := (result).(string)
					return &casted
				}(decoded)
			}(valueHolder)

		case "framework":
			c.Framework = func(param *cffi.CFFIValueHolder) *string {
				decoded := baml.Decode(param)
				return func(result any) *string {
					if result == nil {
						return nil
					}
					casted := (result).(string)
					return &casted
				}(decoded)
			}(valueHolder)

		case "context":
			c.Context = func(param *cffi.CFFIValueHolder) *string {
				decoded := baml.Decode(param)
				return func(result any) *string {
					if result == nil {
						return nil
					}
					casted := (result).(string)
					return &casted
				}(decoded)
			}(valueHolder)

		default:
			panic(fmt.Sprintf("unexpected field: %s", key))
		}
	}

}

func (c BuildOutputCandidate) Encode() (*cffi.CFFIValueHolder, error) {
	fields := map[string]any{}

	fields["default"] = c.Default

	fields["source"] = c.Source

	fields["framework"] = c.Framework

	fields["context"] = c.Context

	return baml.EncodeClass(c.BamlEncodeName, fields, nil)
}

func (c BuildOutputCandidate) BamlTypeName() string {
	return "BuildOutputCandidate"
}

func (u BuildOutputCandidate) BamlEncodeName() *cffi.CFFITypeName {
	return &cffi.CFFITypeName{
		Namespace: cffi.CFFITypeNamespace_STREAM_TYPES,
		Name:      "BuildOutputCandidate",
	}
}

type CategorizedRoutes struct {
	Routes      []Route `json:"routes"`
	Recommended *Route  `json:"recommended"`
}

func (c *CategorizedRoutes) Decode(holder *cffi.CFFIValueClass) {
	typeName := holder.Name
	if typeName.Namespace != cffi.CFFITypeNamespace_STREAM_TYPES {
		panic(fmt.Sprintf("expected cffi.CFFITypeNamespace_STREAM_TYPES, got %s", string(typeName.Namespace.String())))
	}
	if typeName.Name != "CategorizedRoutes" {
		panic(fmt.Sprintf("expected CategorizedRoutes, got %s", typeName.Name))
	}

	for _, field := range holder.Fields {
		key := field.Key
		valueHolder := field.Value
		switch key {

		case "routes":
			c.Routes = baml.DecodeList(valueHolder, func(inner *cffi.CFFIValueHolder) Route {
				return *baml.Decode(inner).(*Route)
			})

		case "recommended":
			c.Recommended = func(param *cffi.CFFIValueHolder) *Route {
				decoded := baml.Decode(param)
				return func(result any) *Route {
					if result == nil {
						return nil
					}
					casted := (result).(*Route)
					return casted
				}(decoded)
			}(valueHolder)

		default:
			panic(fmt.Sprintf("unexpected field: %s", key))
		}
	}

}

func (c CategorizedRoutes) Encode() (*cffi.CFFIValueHolder, error) {
	fields := map[string]any{}

	fields["routes"] = c.Routes

	fields["recommended"] = c.Recommended

	return baml.EncodeClass(c.BamlEncodeName, fields, nil)
}

func (c CategorizedRoutes) BamlTypeName() string {
	return "CategorizedRoutes"
}

func (u CategorizedRoutes) BamlEncodeName() *cffi.CFFITypeName {
	return &cffi.CFFITypeName{
		Namespace: cffi.CFFITypeNamespace_STREAM_TYPES,
		Name:      "CategorizedRoutes",
	}
}

type EnvVarCandidate struct {
	VarName *string `json:"varName"`
	File    *string `json:"file"`
	Line    *int64  `json:"line"`
	Context *string `json:"context"`
}

func (c *EnvVarCandidate) Decode(holder *cffi.CFFIValueClass) {
	typeName := holder.Name
	if typeName.Namespace != cffi.CFFITypeNamespace_STREAM_TYPES {
		panic(fmt.Sprintf("expected cffi.CFFITypeNamespace_STREAM_TYPES, got %s", string(typeName.Namespace.String())))
	}
	if typeName.Name != "EnvVarCandidate" {
		panic(fmt.Sprintf("expected EnvVarCandidate, got %s", typeName.Name))
	}

	for _, field := range holder.Fields {
		key := field.Key
		valueHolder := field.Value
		switch key {

		case "varName":
			c.VarName = func(param *cffi.CFFIValueHolder) *string {
				decoded := baml.Decode(param)
				return func(result any) *string {
					if result == nil {
						return nil
					}
					casted := (result).(string)
					return &casted
				}(decoded)
			}(valueHolder)

		case "file":
			c.File = func(param *cffi.CFFIValueHolder) *string {
				decoded := baml.Decode(param)
				return func(result any) *string {
					if result == nil {
						return nil
					}
					casted := (result).(string)
					return &casted
				}(decoded)
			}(valueHolder)

		case "line":
			c.Line = func(param *cffi.CFFIValueHolder) *int64 {
				decoded := baml.Decode(param)
				return func(result any) *int64 {
					if result == nil {
						return nil
					}
					casted := (result).(int64)
					return &casted
				}(decoded)
			}(valueHolder)

		case "context":
			c.Context = func(param *cffi.CFFIValueHolder) *string {
				decoded := baml.Decode(param)
				return func(result any) *string {
					if result == nil {
						return nil
					}
					casted := (result).(string)
					return &casted
				}(decoded)
			}(valueHolder)

		default:
			panic(fmt.Sprintf("unexpected field: %s", key))
		}
	}

}

func (c EnvVarCandidate) Encode() (*cffi.CFFIValueHolder, error) {
	fields := map[string]any{}

	fields["varName"] = c.VarName

	fields["file"] = c.File

	fields["line"] = c.Line

	fields["context"] = c.Context

	return baml.EncodeClass(c.BamlEncodeName, fields, nil)
}

func (c EnvVarCandidate) BamlTypeName() string {
	return "EnvVarCandidate"
}

func (u EnvVarCandidate) BamlEncodeName() *cffi.CFFITypeName {
	return &cffi.CFFITypeName{
		Namespace: cffi.CFFITypeNamespace_STREAM_TYPES,
		Name:      "EnvVarCandidate",
	}
}

type EnvVarCategory struct {
	IsDBRelated *bool   `json:"isDBRelated"`
	Role        *string `json:"role"`
	DbType      *string `json:"dbType"`
}

func (c *EnvVarCategory) Decode(holder *cffi.CFFIValueClass) {
	typeName := holder.Name
	if typeName.Namespace != cffi.CFFITypeNamespace_STREAM_TYPES {
		panic(fmt.Sprintf("expected cffi.CFFITypeNamespace_STREAM_TYPES, got %s", string(typeName.Namespace.String())))
	}
	if typeName.Name != "EnvVarCategory" {
		panic(fmt.Sprintf("expected EnvVarCategory, got %s", typeName.Name))
	}

	for _, field := range holder.Fields {
		key := field.Key
		valueHolder := field.Value
		switch key {

		case "isDBRelated":
			c.IsDBRelated = func(param *cffi.CFFIValueHolder) *bool {
				decoded := baml.Decode(param)
				return func(result any) *bool {
					if result == nil {
						return nil
					}
					casted := (result).(bool)
					return &casted
				}(decoded)
			}(valueHolder)

		case "role":
			c.Role = func(param *cffi.CFFIValueHolder) *string {
				decoded := baml.Decode(param)
				return func(result any) *string {
					if result == nil {
						return nil
					}
					casted := (result).(string)
					return &casted
				}(decoded)
			}(valueHolder)

		case "dbType":
			c.DbType = func(param *cffi.CFFIValueHolder) *string {
				decoded := baml.Decode(param)
				return func(result any) *string {
					if result == nil {
						return nil
					}
					casted := (result).(string)
					return &casted
				}(decoded)
			}(valueHolder)

		default:
			panic(fmt.Sprintf("unexpected field: %s", key))
		}
	}

}

func (c EnvVarCategory) Encode() (*cffi.CFFIValueHolder, error) {
	fields := map[string]any{}

	fields["isDBRelated"] = c.IsDBRelated

	fields["role"] = c.Role

	fields["dbType"] = c.DbType

	return baml.EncodeClass(c.BamlEncodeName, fields, nil)
}

func (c EnvVarCategory) BamlTypeName() string {
	return "EnvVarCategory"
}

func (u EnvVarCategory) BamlEncodeName() *cffi.CFFITypeName {
	return &cffi.CFFITypeName{
		Namespace: cffi.CFFITypeNamespace_STREAM_TYPES,
		Name:      "EnvVarCategory",
	}
}

type Error struct {
	Summary      *string       `json:"summary"`
	Remediations []Remediation `json:"remediations"`
}

func (c *Error) Decode(holder *cffi.CFFIValueClass) {
	typeName := holder.Name
	if typeName.Namespace != cffi.CFFITypeNamespace_STREAM_TYPES {
		panic(fmt.Sprintf("expected cffi.CFFITypeNamespace_STREAM_TYPES, got %s", string(typeName.Namespace.String())))
	}
	if typeName.Name != "Error" {
		panic(fmt.Sprintf("expected Error, got %s", typeName.Name))
	}

	for _, field := range holder.Fields {
		key := field.Key
		valueHolder := field.Value
		switch key {

		case "summary":
			c.Summary = func(param *cffi.CFFIValueHolder) *string {
				decoded := baml.Decode(param)
				return func(result any) *string {
					if result == nil {
						return nil
					}
					casted := (result).(string)
					return &casted
				}(decoded)
			}(valueHolder)

		case "remediations":
			c.Remediations = baml.DecodeList(valueHolder, func(inner *cffi.CFFIValueHolder) Remediation {
				return *baml.Decode(inner).(*Remediation)
			})

		default:
			panic(fmt.Sprintf("unexpected field: %s", key))
		}
	}

}

func (c Error) Encode() (*cffi.CFFIValueHolder, error) {
	fields := map[string]any{}

	fields["summary"] = c.Summary

	fields["remediations"] = c.Remediations

	return baml.EncodeClass(c.BamlEncodeName, fields, nil)
}

func (c Error) BamlTypeName() string {
	return "Error"
}

func (u Error) BamlEncodeName() *cffi.CFFITypeName {
	return &cffi.CFFITypeName{
		Namespace: cffi.CFFITypeNamespace_STREAM_TYPES,
		Name:      "Error",
	}
}

type Intent struct {
	Action   *string `json:"action"`
	Platform *string `json:"platform"`
	Source   *string `json:"source"`
	DryRun   *bool   `json:"dryRun"`
}

func (c *Intent) Decode(holder *cffi.CFFIValueClass) {
	typeName := holder.Name
	if typeName.Namespace != cffi.CFFITypeNamespace_STREAM_TYPES {
		panic(fmt.Sprintf("expected cffi.CFFITypeNamespace_STREAM_TYPES, got %s", string(typeName.Namespace.String())))
	}
	if typeName.Name != "Intent" {
		panic(fmt.Sprintf("expected Intent, got %s", typeName.Name))
	}

	for _, field := range holder.Fields {
		key := field.Key
		valueHolder := field.Value
		switch key {

		case "action":
			c.Action = func(param *cffi.CFFIValueHolder) *string {
				decoded := baml.Decode(param)
				return func(result any) *string {
					if result == nil {
						return nil
					}
					casted := (result).(string)
					return &casted
				}(decoded)
			}(valueHolder)

		case "platform":
			c.Platform = func(param *cffi.CFFIValueHolder) *string {
				decoded := baml.Decode(param)
				return func(result any) *string {
					if result == nil {
						return nil
					}
					casted := (result).(string)
					return &casted
				}(decoded)
			}(valueHolder)

		case "source":
			c.Source = func(param *cffi.CFFIValueHolder) *string {
				decoded := baml.Decode(param)
				return func(result any) *string {
					if result == nil {
						return nil
					}
					casted := (result).(string)
					return &casted
				}(decoded)
			}(valueHolder)

		case "dryRun":
			c.DryRun = func(param *cffi.CFFIValueHolder) *bool {
				decoded := baml.Decode(param)
				return func(result any) *bool {
					if result == nil {
						return nil
					}
					casted := (result).(bool)
					return &casted
				}(decoded)
			}(valueHolder)

		default:
			panic(fmt.Sprintf("unexpected field: %s", key))
		}
	}

}

func (c Intent) Encode() (*cffi.CFFIValueHolder, error) {
	fields := map[string]any{}

	fields["action"] = c.Action

	fields["platform"] = c.Platform

	fields["source"] = c.Source

	fields["dryRun"] = c.DryRun

	return baml.EncodeClass(c.BamlEncodeName, fields, nil)
}

func (c Intent) BamlTypeName() string {
	return "Intent"
}

func (u Intent) BamlEncodeName() *cffi.CFFITypeName {
	return &cffi.CFFITypeName{
		Namespace: cffi.CFFITypeNamespace_STREAM_TYPES,
		Name:      "Intent",
	}
}

type LaunchCommand struct {
	Command *string `json:"command"`
}

func (c *LaunchCommand) Decode(holder *cffi.CFFIValueClass) {
	typeName := holder.Name
	if typeName.Namespace != cffi.CFFITypeNamespace_STREAM_TYPES {
		panic(fmt.Sprintf("expected cffi.CFFITypeNamespace_STREAM_TYPES, got %s", string(typeName.Namespace.String())))
	}
	if typeName.Name != "LaunchCommand" {
		panic(fmt.Sprintf("expected LaunchCommand, got %s", typeName.Name))
	}

	for _, field := range holder.Fields {
		key := field.Key
		valueHolder := field.Value
		switch key {

		case "command":
			c.Command = func(param *cffi.CFFIValueHolder) *string {
				decoded := baml.Decode(param)
				return func(result any) *string {
					if result == nil {
						return nil
					}
					casted := (result).(string)
					return &casted
				}(decoded)
			}(valueHolder)

		default:
			panic(fmt.Sprintf("unexpected field: %s", key))
		}
	}

}

func (c LaunchCommand) Encode() (*cffi.CFFIValueHolder, error) {
	fields := map[string]any{}

	fields["command"] = c.Command

	return baml.EncodeClass(c.BamlEncodeName, fields, nil)
}

func (c LaunchCommand) BamlTypeName() string {
	return "LaunchCommand"
}

func (u LaunchCommand) BamlEncodeName() *cffi.CFFITypeName {
	return &cffi.CFFITypeName{
		Namespace: cffi.CFFITypeNamespace_STREAM_TYPES,
		Name:      "LaunchCommand",
	}
}

type LaunchContext struct {
	Launchers []LauncherFile `json:"launchers"`
	Readme    *string        `json:"readme"`
}

func (c *LaunchContext) Decode(holder *cffi.CFFIValueClass) {
	typeName := holder.Name
	if typeName.Namespace != cffi.CFFITypeNamespace_STREAM_TYPES {
		panic(fmt.Sprintf("expected cffi.CFFITypeNamespace_STREAM_TYPES, got %s", string(typeName.Namespace.String())))
	}
	if typeName.Name != "LaunchContext" {
		panic(fmt.Sprintf("expected LaunchContext, got %s", typeName.Name))
	}

	for _, field := range holder.Fields {
		key := field.Key
		valueHolder := field.Value
		switch key {

		case "launchers":
			c.Launchers = baml.DecodeList(valueHolder, func(inner *cffi.CFFIValueHolder) LauncherFile {
				return *baml.Decode(inner).(*LauncherFile)
			})

		case "readme":
			c.Readme = func(param *cffi.CFFIValueHolder) *string {
				decoded := baml.Decode(param)
				return func(result any) *string {
					if result == nil {
						return nil
					}
					casted := (result).(string)
					return &casted
				}(decoded)
			}(valueHolder)

		default:
			panic(fmt.Sprintf("unexpected field: %s", key))
		}
	}

}

func (c LaunchContext) Encode() (*cffi.CFFIValueHolder, error) {
	fields := map[string]any{}

	fields["launchers"] = c.Launchers

	fields["readme"] = c.Readme

	return baml.EncodeClass(c.BamlEncodeName, fields, nil)
}

func (c LaunchContext) BamlTypeName() string {
	return "LaunchContext"
}

func (u LaunchContext) BamlEncodeName() *cffi.CFFITypeName {
	return &cffi.CFFITypeName{
		Namespace: cffi.CFFITypeNamespace_STREAM_TYPES,
		Name:      "LaunchContext",
	}
}

type LauncherFile struct {
	Name    *string `json:"name"`
	Content *string `json:"content"`
}

func (c *LauncherFile) Decode(holder *cffi.CFFIValueClass) {
	typeName := holder.Name
	if typeName.Namespace != cffi.CFFITypeNamespace_STREAM_TYPES {
		panic(fmt.Sprintf("expected cffi.CFFITypeNamespace_STREAM_TYPES, got %s", string(typeName.Namespace.String())))
	}
	if typeName.Name != "LauncherFile" {
		panic(fmt.Sprintf("expected LauncherFile, got %s", typeName.Name))
	}

	for _, field := range holder.Fields {
		key := field.Key
		valueHolder := field.Value
		switch key {

		case "name":
			c.Name = func(param *cffi.CFFIValueHolder) *string {
				decoded := baml.Decode(param)
				return func(result any) *string {
					if result == nil {
						return nil
					}
					casted := (result).(string)
					return &casted
				}(decoded)
			}(valueHolder)

		case "content":
			c.Content = func(param *cffi.CFFIValueHolder) *string {
				decoded := baml.Decode(param)
				return func(result any) *string {
					if result == nil {
						return nil
					}
					casted := (result).(string)
					return &casted
				}(decoded)
			}(valueHolder)

		default:
			panic(fmt.Sprintf("unexpected field: %s", key))
		}
	}

}

func (c LauncherFile) Encode() (*cffi.CFFIValueHolder, error) {
	fields := map[string]any{}

	fields["name"] = c.Name

	fields["content"] = c.Content

	return baml.EncodeClass(c.BamlEncodeName, fields, nil)
}

func (c LauncherFile) BamlTypeName() string {
	return "LauncherFile"
}

func (u LauncherFile) BamlEncodeName() *cffi.CFFITypeName {
	return &cffi.CFFITypeName{
		Namespace: cffi.CFFITypeNamespace_STREAM_TYPES,
		Name:      "LauncherFile",
	}
}

type PricingResponse struct {
	Services   []ServicePricing `json:"services"`
	Total_cost *float64         `json:"total_cost"`
}

func (c *PricingResponse) Decode(holder *cffi.CFFIValueClass) {
	typeName := holder.Name
	if typeName.Namespace != cffi.CFFITypeNamespace_STREAM_TYPES {
		panic(fmt.Sprintf("expected cffi.CFFITypeNamespace_STREAM_TYPES, got %s", string(typeName.Namespace.String())))
	}
	if typeName.Name != "PricingResponse" {
		panic(fmt.Sprintf("expected PricingResponse, got %s", typeName.Name))
	}

	for _, field := range holder.Fields {
		key := field.Key
		valueHolder := field.Value
		switch key {

		case "services":
			c.Services = baml.DecodeList(valueHolder, func(inner *cffi.CFFIValueHolder) ServicePricing {
				return *baml.Decode(inner).(*ServicePricing)
			})

		case "total_cost":
			c.Total_cost = func(param *cffi.CFFIValueHolder) *float64 {
				decoded := baml.Decode(param)
				return func(result any) *float64 {
					if result == nil {
						return nil
					}
					casted := (result).(float64)
					return &casted
				}(decoded)
			}(valueHolder)

		default:
			panic(fmt.Sprintf("unexpected field: %s", key))
		}
	}

}

func (c PricingResponse) Encode() (*cffi.CFFIValueHolder, error) {
	fields := map[string]any{}

	fields["services"] = c.Services

	fields["total_cost"] = c.Total_cost

	return baml.EncodeClass(c.BamlEncodeName, fields, nil)
}

func (c PricingResponse) BamlTypeName() string {
	return "PricingResponse"
}

func (u PricingResponse) BamlEncodeName() *cffi.CFFITypeName {
	return &cffi.CFFITypeName{
		Namespace: cffi.CFFITypeNamespace_STREAM_TYPES,
		Name:      "PricingResponse",
	}
}

type ProjectSpec struct {
	Name                *string              `json:"name"`
	Language            *string              `json:"language"`
	ServiceRequirements []ServiceRequirement `json:"serviceRequirements"`
	BuildCommand        *string              `json:"buildCommand"`
	StartCommand        *string              `json:"startCommand"`
}

func (c *ProjectSpec) Decode(holder *cffi.CFFIValueClass) {
	typeName := holder.Name
	if typeName.Namespace != cffi.CFFITypeNamespace_STREAM_TYPES {
		panic(fmt.Sprintf("expected cffi.CFFITypeNamespace_STREAM_TYPES, got %s", string(typeName.Namespace.String())))
	}
	if typeName.Name != "ProjectSpec" {
		panic(fmt.Sprintf("expected ProjectSpec, got %s", typeName.Name))
	}

	for _, field := range holder.Fields {
		key := field.Key
		valueHolder := field.Value
		switch key {

		case "name":
			c.Name = func(param *cffi.CFFIValueHolder) *string {
				decoded := baml.Decode(param)
				return func(result any) *string {
					if result == nil {
						return nil
					}
					casted := (result).(string)
					return &casted
				}(decoded)
			}(valueHolder)

		case "language":
			c.Language = func(param *cffi.CFFIValueHolder) *string {
				decoded := baml.Decode(param)
				return func(result any) *string {
					if result == nil {
						return nil
					}
					casted := (result).(string)
					return &casted
				}(decoded)
			}(valueHolder)

		case "serviceRequirements":
			c.ServiceRequirements = baml.DecodeList(valueHolder, func(inner *cffi.CFFIValueHolder) ServiceRequirement {
				return *baml.Decode(inner).(*ServiceRequirement)
			})

		case "buildCommand":
			c.BuildCommand = func(param *cffi.CFFIValueHolder) *string {
				decoded := baml.Decode(param)
				return func(result any) *string {
					if result == nil {
						return nil
					}
					casted := (result).(string)
					return &casted
				}(decoded)
			}(valueHolder)

		case "startCommand":
			c.StartCommand = func(param *cffi.CFFIValueHolder) *string {
				decoded := baml.Decode(param)
				return func(result any) *string {
					if result == nil {
						return nil
					}
					casted := (result).(string)
					return &casted
				}(decoded)
			}(valueHolder)

		default:
			panic(fmt.Sprintf("unexpected field: %s", key))
		}
	}

}

func (c ProjectSpec) Encode() (*cffi.CFFIValueHolder, error) {
	fields := map[string]any{}

	fields["name"] = c.Name

	fields["language"] = c.Language

	fields["serviceRequirements"] = c.ServiceRequirements

	fields["buildCommand"] = c.BuildCommand

	fields["startCommand"] = c.StartCommand

	return baml.EncodeClass(c.BamlEncodeName, fields, nil)
}

func (c ProjectSpec) BamlTypeName() string {
	return "ProjectSpec"
}

func (u ProjectSpec) BamlEncodeName() *cffi.CFFITypeName {
	return &cffi.CFFITypeName{
		Namespace: cffi.CFFITypeNamespace_STREAM_TYPES,
		Name:      "ProjectSpec",
	}
}

type Remediation struct {
	Description *string `json:"description"`
	CliCommand  *string `json:"cliCommand"`
}

func (c *Remediation) Decode(holder *cffi.CFFIValueClass) {
	typeName := holder.Name
	if typeName.Namespace != cffi.CFFITypeNamespace_STREAM_TYPES {
		panic(fmt.Sprintf("expected cffi.CFFITypeNamespace_STREAM_TYPES, got %s", string(typeName.Namespace.String())))
	}
	if typeName.Name != "Remediation" {
		panic(fmt.Sprintf("expected Remediation, got %s", typeName.Name))
	}

	for _, field := range holder.Fields {
		key := field.Key
		valueHolder := field.Value
		switch key {

		case "description":
			c.Description = func(param *cffi.CFFIValueHolder) *string {
				decoded := baml.Decode(param)
				return func(result any) *string {
					if result == nil {
						return nil
					}
					casted := (result).(string)
					return &casted
				}(decoded)
			}(valueHolder)

		case "cliCommand":
			c.CliCommand = func(param *cffi.CFFIValueHolder) *string {
				decoded := baml.Decode(param)
				return func(result any) *string {
					if result == nil {
						return nil
					}
					casted := (result).(string)
					return &casted
				}(decoded)
			}(valueHolder)

		default:
			panic(fmt.Sprintf("unexpected field: %s", key))
		}
	}

}

func (c Remediation) Encode() (*cffi.CFFIValueHolder, error) {
	fields := map[string]any{}

	fields["description"] = c.Description

	fields["cliCommand"] = c.CliCommand

	return baml.EncodeClass(c.BamlEncodeName, fields, nil)
}

func (c Remediation) BamlTypeName() string {
	return "Remediation"
}

func (u Remediation) BamlEncodeName() *cffi.CFFITypeName {
	return &cffi.CFFITypeName{
		Namespace: cffi.CFFITypeNamespace_STREAM_TYPES,
		Name:      "Remediation",
	}
}

type Route struct {
	Method     *string  `json:"method"`
	Path       *string  `json:"path"`
	Confidence *float64 `json:"confidence"`
}

func (c *Route) Decode(holder *cffi.CFFIValueClass) {
	typeName := holder.Name
	if typeName.Namespace != cffi.CFFITypeNamespace_STREAM_TYPES {
		panic(fmt.Sprintf("expected cffi.CFFITypeNamespace_STREAM_TYPES, got %s", string(typeName.Namespace.String())))
	}
	if typeName.Name != "Route" {
		panic(fmt.Sprintf("expected Route, got %s", typeName.Name))
	}

	for _, field := range holder.Fields {
		key := field.Key
		valueHolder := field.Value
		switch key {

		case "method":
			c.Method = func(param *cffi.CFFIValueHolder) *string {
				decoded := baml.Decode(param)
				return func(result any) *string {
					if result == nil {
						return nil
					}
					casted := (result).(string)
					return &casted
				}(decoded)
			}(valueHolder)

		case "path":
			c.Path = func(param *cffi.CFFIValueHolder) *string {
				decoded := baml.Decode(param)
				return func(result any) *string {
					if result == nil {
						return nil
					}
					casted := (result).(string)
					return &casted
				}(decoded)
			}(valueHolder)

		case "confidence":
			c.Confidence = func(param *cffi.CFFIValueHolder) *float64 {
				decoded := baml.Decode(param)
				return func(result any) *float64 {
					if result == nil {
						return nil
					}
					casted := (result).(float64)
					return &casted
				}(decoded)
			}(valueHolder)

		default:
			panic(fmt.Sprintf("unexpected field: %s", key))
		}
	}

}

func (c Route) Encode() (*cffi.CFFIValueHolder, error) {
	fields := map[string]any{}

	fields["method"] = c.Method

	fields["path"] = c.Path

	fields["confidence"] = c.Confidence

	return baml.EncodeClass(c.BamlEncodeName, fields, nil)
}

func (c Route) BamlTypeName() string {
	return "Route"
}

func (u Route) BamlEncodeName() *cffi.CFFITypeName {
	return &cffi.CFFITypeName{
		Namespace: cffi.CFFITypeNamespace_STREAM_TYPES,
		Name:      "Route",
	}
}

type RouteCandidate struct {
	Method  *string `json:"method"`
	Path    *string `json:"path"`
	File    *string `json:"file"`
	Line    *int64  `json:"line"`
	Context *string `json:"context"`
}

func (c *RouteCandidate) Decode(holder *cffi.CFFIValueClass) {
	typeName := holder.Name
	if typeName.Namespace != cffi.CFFITypeNamespace_STREAM_TYPES {
		panic(fmt.Sprintf("expected cffi.CFFITypeNamespace_STREAM_TYPES, got %s", string(typeName.Namespace.String())))
	}
	if typeName.Name != "RouteCandidate" {
		panic(fmt.Sprintf("expected RouteCandidate, got %s", typeName.Name))
	}

	for _, field := range holder.Fields {
		key := field.Key
		valueHolder := field.Value
		switch key {

		case "method":
			c.Method = func(param *cffi.CFFIValueHolder) *string {
				decoded := baml.Decode(param)
				return func(result any) *string {
					if result == nil {
						return nil
					}
					casted := (result).(string)
					return &casted
				}(decoded)
			}(valueHolder)

		case "path":
			c.Path = func(param *cffi.CFFIValueHolder) *string {
				decoded := baml.Decode(param)
				return func(result any) *string {
					if result == nil {
						return nil
					}
					casted := (result).(string)
					return &casted
				}(decoded)
			}(valueHolder)

		case "file":
			c.File = func(param *cffi.CFFIValueHolder) *string {
				decoded := baml.Decode(param)
				return func(result any) *string {
					if result == nil {
						return nil
					}
					casted := (result).(string)
					return &casted
				}(decoded)
			}(valueHolder)

		case "line":
			c.Line = func(param *cffi.CFFIValueHolder) *int64 {
				decoded := baml.Decode(param)
				return func(result any) *int64 {
					if result == nil {
						return nil
					}
					casted := (result).(int64)
					return &casted
				}(decoded)
			}(valueHolder)

		case "context":
			c.Context = func(param *cffi.CFFIValueHolder) *string {
				decoded := baml.Decode(param)
				return func(result any) *string {
					if result == nil {
						return nil
					}
					casted := (result).(string)
					return &casted
				}(decoded)
			}(valueHolder)

		default:
			panic(fmt.Sprintf("unexpected field: %s", key))
		}
	}

}

func (c RouteCandidate) Encode() (*cffi.CFFIValueHolder, error) {
	fields := map[string]any{}

	fields["method"] = c.Method

	fields["path"] = c.Path

	fields["file"] = c.File

	fields["line"] = c.Line

	fields["context"] = c.Context

	return baml.EncodeClass(c.BamlEncodeName, fields, nil)
}

func (c RouteCandidate) BamlTypeName() string {
	return "RouteCandidate"
}

func (u RouteCandidate) BamlEncodeName() *cffi.CFFITypeName {
	return &cffi.CFFITypeName{
		Namespace: cffi.CFFITypeNamespace_STREAM_TYPES,
		Name:      "RouteCandidate",
	}
}

type ServicePricing struct {
	Service_name *string  `json:"service_name"`
	Service_type *string  `json:"service_type"`
	Plan         *string  `json:"plan"`
	Monthly_cost *float64 `json:"monthly_cost"`
}

func (c *ServicePricing) Decode(holder *cffi.CFFIValueClass) {
	typeName := holder.Name
	if typeName.Namespace != cffi.CFFITypeNamespace_STREAM_TYPES {
		panic(fmt.Sprintf("expected cffi.CFFITypeNamespace_STREAM_TYPES, got %s", string(typeName.Namespace.String())))
	}
	if typeName.Name != "ServicePricing" {
		panic(fmt.Sprintf("expected ServicePricing, got %s", typeName.Name))
	}

	for _, field := range holder.Fields {
		key := field.Key
		valueHolder := field.Value
		switch key {

		case "service_name":
			c.Service_name = func(param *cffi.CFFIValueHolder) *string {
				decoded := baml.Decode(param)
				return func(result any) *string {
					if result == nil {
						return nil
					}
					casted := (result).(string)
					return &casted
				}(decoded)
			}(valueHolder)

		case "service_type":
			c.Service_type = func(param *cffi.CFFIValueHolder) *string {
				decoded := baml.Decode(param)
				return func(result any) *string {
					if result == nil {
						return nil
					}
					casted := (result).(string)
					return &casted
				}(decoded)
			}(valueHolder)

		case "plan":
			c.Plan = func(param *cffi.CFFIValueHolder) *string {
				decoded := baml.Decode(param)
				return func(result any) *string {
					if result == nil {
						return nil
					}
					casted := (result).(string)
					return &casted
				}(decoded)
			}(valueHolder)

		case "monthly_cost":
			c.Monthly_cost = func(param *cffi.CFFIValueHolder) *float64 {
				decoded := baml.Decode(param)
				return func(result any) *float64 {
					if result == nil {
						return nil
					}
					casted := (result).(float64)
					return &casted
				}(decoded)
			}(valueHolder)

		default:
			panic(fmt.Sprintf("unexpected field: %s", key))
		}
	}

}

func (c ServicePricing) Encode() (*cffi.CFFIValueHolder, error) {
	fields := map[string]any{}

	fields["service_name"] = c.Service_name

	fields["service_type"] = c.Service_type

	fields["plan"] = c.Plan

	fields["monthly_cost"] = c.Monthly_cost

	return baml.EncodeClass(c.BamlEncodeName, fields, nil)
}

func (c ServicePricing) BamlTypeName() string {
	return "ServicePricing"
}

func (u ServicePricing) BamlEncodeName() *cffi.CFFITypeName {
	return &cffi.CFFITypeName{
		Namespace: cffi.CFFITypeNamespace_STREAM_TYPES,
		Name:      "ServicePricing",
	}
}

type ServiceRequirement struct {
	Type     *string `json:"type"`
	Provider *string `json:"provider"`
}

func (c *ServiceRequirement) Decode(holder *cffi.CFFIValueClass) {
	typeName := holder.Name
	if typeName.Namespace != cffi.CFFITypeNamespace_STREAM_TYPES {
		panic(fmt.Sprintf("expected cffi.CFFITypeNamespace_STREAM_TYPES, got %s", string(typeName.Namespace.String())))
	}
	if typeName.Name != "ServiceRequirement" {
		panic(fmt.Sprintf("expected ServiceRequirement, got %s", typeName.Name))
	}

	for _, field := range holder.Fields {
		key := field.Key
		valueHolder := field.Value
		switch key {

		case "type":
			c.Type = func(param *cffi.CFFIValueHolder) *string {
				decoded := baml.Decode(param)
				return func(result any) *string {
					if result == nil {
						return nil
					}
					casted := (result).(string)
					return &casted
				}(decoded)
			}(valueHolder)

		case "provider":
			c.Provider = func(param *cffi.CFFIValueHolder) *string {
				decoded := baml.Decode(param)
				return func(result any) *string {
					if result == nil {
						return nil
					}
					casted := (result).(string)
					return &casted
				}(decoded)
			}(valueHolder)

		default:
			panic(fmt.Sprintf("unexpected field: %s", key))
		}
	}

}

func (c ServiceRequirement) Encode() (*cffi.CFFIValueHolder, error) {
	fields := map[string]any{}

	fields["type"] = c.Type

	fields["provider"] = c.Provider

	return baml.EncodeClass(c.BamlEncodeName, fields, nil)
}

func (c ServiceRequirement) BamlTypeName() string {
	return "ServiceRequirement"
}

func (u ServiceRequirement) BamlEncodeName() *cffi.CFFITypeName {
	return &cffi.CFFITypeName{
		Namespace: cffi.CFFITypeNamespace_STREAM_TYPES,
		Name:      "ServiceRequirement",
	}
}

type Summary struct {
	Summary *string `json:"summary"`
}

func (c *Summary) Decode(holder *cffi.CFFIValueClass) {
	typeName := holder.Name
	if typeName.Namespace != cffi.CFFITypeNamespace_STREAM_TYPES {
		panic(fmt.Sprintf("expected cffi.CFFITypeNamespace_STREAM_TYPES, got %s", string(typeName.Namespace.String())))
	}
	if typeName.Name != "Summary" {
		panic(fmt.Sprintf("expected Summary, got %s", typeName.Name))
	}

	for _, field := range holder.Fields {
		key := field.Key
		valueHolder := field.Value
		switch key {

		case "summary":
			c.Summary = func(param *cffi.CFFIValueHolder) *string {
				decoded := baml.Decode(param)
				return func(result any) *string {
					if result == nil {
						return nil
					}
					casted := (result).(string)
					return &casted
				}(decoded)
			}(valueHolder)

		default:
			panic(fmt.Sprintf("unexpected field: %s", key))
		}
	}

}

func (c Summary) Encode() (*cffi.CFFIValueHolder, error) {
	fields := map[string]any{}

	fields["summary"] = c.Summary

	return baml.EncodeClass(c.BamlEncodeName, fields, nil)
}

func (c Summary) BamlTypeName() string {
	return "Summary"
}

func (u Summary) BamlEncodeName() *cffi.CFFITypeName {
	return &cffi.CFFITypeName{
		Namespace: cffi.CFFITypeNamespace_STREAM_TYPES,
		Name:      "Summary",
	}
}
