// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ go get github.com/boundaryml/baml
//
// ----------------------------------------------------------------------------

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ go install github.com/boundaryml/baml/baml-cli

package type_builder

import baml "github.com/boundaryml/baml/engine/language_client_go/pkg"

type BuildOutputClassView struct {
	inner baml.ClassBuilder
}

func (t *BuildOutputClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *BuildOutputClassView) PropertyPath() (ClassPropertyView, error) {
	return t.inner.Property("path")
}

func (t *TypeBuilder) BuildOutput() (*BuildOutputClassView, error) {
	bld, err := t.inner.Class("BuildOutput")
	if err != nil {
		return nil, err
	}
	return &BuildOutputClassView{inner: bld}, nil
}

func (t *BuildOutputClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type BuildOutputCandidateClassView struct {
	inner baml.ClassBuilder
}

func (t *BuildOutputCandidateClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *BuildOutputCandidateClassView) PropertyDefault() (ClassPropertyView, error) {
	return t.inner.Property("default")
}

func (t *BuildOutputCandidateClassView) PropertySource() (ClassPropertyView, error) {
	return t.inner.Property("source")
}

func (t *BuildOutputCandidateClassView) PropertyFramework() (ClassPropertyView, error) {
	return t.inner.Property("framework")
}

func (t *BuildOutputCandidateClassView) PropertyContext() (ClassPropertyView, error) {
	return t.inner.Property("context")
}

func (t *TypeBuilder) BuildOutputCandidate() (*BuildOutputCandidateClassView, error) {
	bld, err := t.inner.Class("BuildOutputCandidate")
	if err != nil {
		return nil, err
	}
	return &BuildOutputCandidateClassView{inner: bld}, nil
}

func (t *BuildOutputCandidateClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type CategorizedRoutesClassView struct {
	inner baml.ClassBuilder
}

func (t *CategorizedRoutesClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *CategorizedRoutesClassView) PropertyRoutes() (ClassPropertyView, error) {
	return t.inner.Property("routes")
}

func (t *CategorizedRoutesClassView) PropertyRecommended() (ClassPropertyView, error) {
	return t.inner.Property("recommended")
}

func (t *TypeBuilder) CategorizedRoutes() (*CategorizedRoutesClassView, error) {
	bld, err := t.inner.Class("CategorizedRoutes")
	if err != nil {
		return nil, err
	}
	return &CategorizedRoutesClassView{inner: bld}, nil
}

func (t *CategorizedRoutesClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type EnvVarCandidateClassView struct {
	inner baml.ClassBuilder
}

func (t *EnvVarCandidateClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *EnvVarCandidateClassView) PropertyVarName() (ClassPropertyView, error) {
	return t.inner.Property("varName")
}

func (t *EnvVarCandidateClassView) PropertyFile() (ClassPropertyView, error) {
	return t.inner.Property("file")
}

func (t *EnvVarCandidateClassView) PropertyLine() (ClassPropertyView, error) {
	return t.inner.Property("line")
}

func (t *EnvVarCandidateClassView) PropertyContext() (ClassPropertyView, error) {
	return t.inner.Property("context")
}

func (t *TypeBuilder) EnvVarCandidate() (*EnvVarCandidateClassView, error) {
	bld, err := t.inner.Class("EnvVarCandidate")
	if err != nil {
		return nil, err
	}
	return &EnvVarCandidateClassView{inner: bld}, nil
}

func (t *EnvVarCandidateClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type EnvVarCategoryClassView struct {
	inner baml.ClassBuilder
}

func (t *EnvVarCategoryClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *EnvVarCategoryClassView) PropertyIsDBRelated() (ClassPropertyView, error) {
	return t.inner.Property("isDBRelated")
}

func (t *EnvVarCategoryClassView) PropertyRole() (ClassPropertyView, error) {
	return t.inner.Property("role")
}

func (t *EnvVarCategoryClassView) PropertyDbType() (ClassPropertyView, error) {
	return t.inner.Property("dbType")
}

func (t *EnvVarCategoryClassView) PropertyIsSensitive() (ClassPropertyView, error) {
	return t.inner.Property("isSensitive")
}

func (t *EnvVarCategoryClassView) PropertySensitivityReason() (ClassPropertyView, error) {
	return t.inner.Property("sensitivityReason")
}

func (t *TypeBuilder) EnvVarCategory() (*EnvVarCategoryClassView, error) {
	bld, err := t.inner.Class("EnvVarCategory")
	if err != nil {
		return nil, err
	}
	return &EnvVarCategoryClassView{inner: bld}, nil
}

func (t *EnvVarCategoryClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type ErrorClassView struct {
	inner baml.ClassBuilder
}

func (t *ErrorClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *ErrorClassView) PropertySummary() (ClassPropertyView, error) {
	return t.inner.Property("summary")
}

func (t *ErrorClassView) PropertyRemediations() (ClassPropertyView, error) {
	return t.inner.Property("remediations")
}

func (t *TypeBuilder) Error() (*ErrorClassView, error) {
	bld, err := t.inner.Class("Error")
	if err != nil {
		return nil, err
	}
	return &ErrorClassView{inner: bld}, nil
}

func (t *ErrorClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type IntentClassView struct {
	inner baml.ClassBuilder
}

func (t *IntentClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *IntentClassView) PropertyAction() (ClassPropertyView, error) {
	return t.inner.Property("action")
}

func (t *IntentClassView) PropertyPlatform() (ClassPropertyView, error) {
	return t.inner.Property("platform")
}

func (t *IntentClassView) PropertySource() (ClassPropertyView, error) {
	return t.inner.Property("source")
}

func (t *TypeBuilder) Intent() (*IntentClassView, error) {
	bld, err := t.inner.Class("Intent")
	if err != nil {
		return nil, err
	}
	return &IntentClassView{inner: bld}, nil
}

func (t *IntentClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type LaunchCommandClassView struct {
	inner baml.ClassBuilder
}

func (t *LaunchCommandClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *LaunchCommandClassView) PropertyCommand() (ClassPropertyView, error) {
	return t.inner.Property("command")
}

func (t *TypeBuilder) LaunchCommand() (*LaunchCommandClassView, error) {
	bld, err := t.inner.Class("LaunchCommand")
	if err != nil {
		return nil, err
	}
	return &LaunchCommandClassView{inner: bld}, nil
}

func (t *LaunchCommandClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type LaunchContextClassView struct {
	inner baml.ClassBuilder
}

func (t *LaunchContextClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *LaunchContextClassView) PropertyLaunchers() (ClassPropertyView, error) {
	return t.inner.Property("launchers")
}

func (t *LaunchContextClassView) PropertyReadme() (ClassPropertyView, error) {
	return t.inner.Property("readme")
}

func (t *TypeBuilder) LaunchContext() (*LaunchContextClassView, error) {
	bld, err := t.inner.Class("LaunchContext")
	if err != nil {
		return nil, err
	}
	return &LaunchContextClassView{inner: bld}, nil
}

func (t *LaunchContextClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type LauncherFileClassView struct {
	inner baml.ClassBuilder
}

func (t *LauncherFileClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *LauncherFileClassView) PropertyName() (ClassPropertyView, error) {
	return t.inner.Property("name")
}

func (t *LauncherFileClassView) PropertyContent() (ClassPropertyView, error) {
	return t.inner.Property("content")
}

func (t *TypeBuilder) LauncherFile() (*LauncherFileClassView, error) {
	bld, err := t.inner.Class("LauncherFile")
	if err != nil {
		return nil, err
	}
	return &LauncherFileClassView{inner: bld}, nil
}

func (t *LauncherFileClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type MigrationCommandClassView struct {
	inner baml.ClassBuilder
}

func (t *MigrationCommandClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *MigrationCommandClassView) PropertyCommand() (ClassPropertyView, error) {
	return t.inner.Property("command")
}

func (t *MigrationCommandClassView) PropertyConfidence() (ClassPropertyView, error) {
	return t.inner.Property("confidence")
}

func (t *MigrationCommandClassView) PropertyExplanation() (ClassPropertyView, error) {
	return t.inner.Property("explanation")
}

func (t *TypeBuilder) MigrationCommand() (*MigrationCommandClassView, error) {
	bld, err := t.inner.Class("MigrationCommand")
	if err != nil {
		return nil, err
	}
	return &MigrationCommandClassView{inner: bld}, nil
}

func (t *MigrationCommandClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type MigrationContextClassView struct {
	inner baml.ClassBuilder
}

func (t *MigrationContextClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *MigrationContextClassView) PropertyMigrationFiles() (ClassPropertyView, error) {
	return t.inner.Property("migrationFiles")
}

func (t *MigrationContextClassView) PropertyOrmTools() (ClassPropertyView, error) {
	return t.inner.Property("ormTools")
}

func (t *MigrationContextClassView) PropertyPackageScripts() (ClassPropertyView, error) {
	return t.inner.Property("packageScripts")
}

func (t *MigrationContextClassView) PropertyConfigSnippets() (ClassPropertyView, error) {
	return t.inner.Property("configSnippets")
}

func (t *TypeBuilder) MigrationContext() (*MigrationContextClassView, error) {
	bld, err := t.inner.Class("MigrationContext")
	if err != nil {
		return nil, err
	}
	return &MigrationContextClassView{inner: bld}, nil
}

func (t *MigrationContextClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type MigrationFileClassView struct {
	inner baml.ClassBuilder
}

func (t *MigrationFileClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *MigrationFileClassView) PropertyPath() (ClassPropertyView, error) {
	return t.inner.Property("path")
}

func (t *MigrationFileClassView) PropertyType() (ClassPropertyView, error) {
	return t.inner.Property("type")
}

func (t *TypeBuilder) MigrationFile() (*MigrationFileClassView, error) {
	bld, err := t.inner.Class("MigrationFile")
	if err != nil {
		return nil, err
	}
	return &MigrationFileClassView{inner: bld}, nil
}

func (t *MigrationFileClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type PricingResponseClassView struct {
	inner baml.ClassBuilder
}

func (t *PricingResponseClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *PricingResponseClassView) PropertyServices() (ClassPropertyView, error) {
	return t.inner.Property("services")
}

func (t *PricingResponseClassView) PropertyTotal_cost() (ClassPropertyView, error) {
	return t.inner.Property("total_cost")
}

func (t *TypeBuilder) PricingResponse() (*PricingResponseClassView, error) {
	bld, err := t.inner.Class("PricingResponse")
	if err != nil {
		return nil, err
	}
	return &PricingResponseClassView{inner: bld}, nil
}

func (t *PricingResponseClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type ProjectSpecClassView struct {
	inner baml.ClassBuilder
}

func (t *ProjectSpecClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *ProjectSpecClassView) PropertyName() (ClassPropertyView, error) {
	return t.inner.Property("name")
}

func (t *ProjectSpecClassView) PropertyLanguage() (ClassPropertyView, error) {
	return t.inner.Property("language")
}

func (t *ProjectSpecClassView) PropertyServiceRequirements() (ClassPropertyView, error) {
	return t.inner.Property("serviceRequirements")
}

func (t *ProjectSpecClassView) PropertyBuildCommand() (ClassPropertyView, error) {
	return t.inner.Property("buildCommand")
}

func (t *ProjectSpecClassView) PropertyStartCommand() (ClassPropertyView, error) {
	return t.inner.Property("startCommand")
}

func (t *TypeBuilder) ProjectSpec() (*ProjectSpecClassView, error) {
	bld, err := t.inner.Class("ProjectSpec")
	if err != nil {
		return nil, err
	}
	return &ProjectSpecClassView{inner: bld}, nil
}

func (t *ProjectSpecClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type RemediationClassView struct {
	inner baml.ClassBuilder
}

func (t *RemediationClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *RemediationClassView) PropertyDescription() (ClassPropertyView, error) {
	return t.inner.Property("description")
}

func (t *RemediationClassView) PropertyCliCommand() (ClassPropertyView, error) {
	return t.inner.Property("cliCommand")
}

func (t *TypeBuilder) Remediation() (*RemediationClassView, error) {
	bld, err := t.inner.Class("Remediation")
	if err != nil {
		return nil, err
	}
	return &RemediationClassView{inner: bld}, nil
}

func (t *RemediationClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type RouteClassView struct {
	inner baml.ClassBuilder
}

func (t *RouteClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *RouteClassView) PropertyMethod() (ClassPropertyView, error) {
	return t.inner.Property("method")
}

func (t *RouteClassView) PropertyPath() (ClassPropertyView, error) {
	return t.inner.Property("path")
}

func (t *RouteClassView) PropertyConfidence() (ClassPropertyView, error) {
	return t.inner.Property("confidence")
}

func (t *TypeBuilder) Route() (*RouteClassView, error) {
	bld, err := t.inner.Class("Route")
	if err != nil {
		return nil, err
	}
	return &RouteClassView{inner: bld}, nil
}

func (t *RouteClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type RouteCandidateClassView struct {
	inner baml.ClassBuilder
}

func (t *RouteCandidateClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *RouteCandidateClassView) PropertyMethod() (ClassPropertyView, error) {
	return t.inner.Property("method")
}

func (t *RouteCandidateClassView) PropertyPath() (ClassPropertyView, error) {
	return t.inner.Property("path")
}

func (t *RouteCandidateClassView) PropertyFile() (ClassPropertyView, error) {
	return t.inner.Property("file")
}

func (t *RouteCandidateClassView) PropertyLine() (ClassPropertyView, error) {
	return t.inner.Property("line")
}

func (t *RouteCandidateClassView) PropertyContext() (ClassPropertyView, error) {
	return t.inner.Property("context")
}

func (t *TypeBuilder) RouteCandidate() (*RouteCandidateClassView, error) {
	bld, err := t.inner.Class("RouteCandidate")
	if err != nil {
		return nil, err
	}
	return &RouteCandidateClassView{inner: bld}, nil
}

func (t *RouteCandidateClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type ServiceClassView struct {
	inner baml.ClassBuilder
}

func (t *ServiceClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *ServiceClassView) PropertyName() (ClassPropertyView, error) {
	return t.inner.Property("name")
}

func (t *ServiceClassView) PropertyType() (ClassPropertyView, error) {
	return t.inner.Property("type")
}

func (t *ServiceClassView) PropertyPlan() (ClassPropertyView, error) {
	return t.inner.Property("plan")
}

func (t *ServiceClassView) PropertyStorage() (ClassPropertyView, error) {
	return t.inner.Property("storage")
}

func (t *TypeBuilder) Service() (*ServiceClassView, error) {
	bld, err := t.inner.Class("Service")
	if err != nil {
		return nil, err
	}
	return &ServiceClassView{inner: bld}, nil
}

func (t *ServiceClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type ServicePricingClassView struct {
	inner baml.ClassBuilder
}

func (t *ServicePricingClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *ServicePricingClassView) PropertyService_name() (ClassPropertyView, error) {
	return t.inner.Property("service_name")
}

func (t *ServicePricingClassView) PropertyService_type() (ClassPropertyView, error) {
	return t.inner.Property("service_type")
}

func (t *ServicePricingClassView) PropertyPlan() (ClassPropertyView, error) {
	return t.inner.Property("plan")
}

func (t *ServicePricingClassView) PropertyMonthly_cost() (ClassPropertyView, error) {
	return t.inner.Property("monthly_cost")
}

func (t *ServicePricingClassView) PropertyUsage_cost() (ClassPropertyView, error) {
	return t.inner.Property("usage_cost")
}

func (t *TypeBuilder) ServicePricing() (*ServicePricingClassView, error) {
	bld, err := t.inner.Class("ServicePricing")
	if err != nil {
		return nil, err
	}
	return &ServicePricingClassView{inner: bld}, nil
}

func (t *ServicePricingClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type ServiceRequirementClassView struct {
	inner baml.ClassBuilder
}

func (t *ServiceRequirementClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *ServiceRequirementClassView) PropertyType() (ClassPropertyView, error) {
	return t.inner.Property("type")
}

func (t *ServiceRequirementClassView) PropertyProvider() (ClassPropertyView, error) {
	return t.inner.Property("provider")
}

func (t *TypeBuilder) ServiceRequirement() (*ServiceRequirementClassView, error) {
	bld, err := t.inner.Class("ServiceRequirement")
	if err != nil {
		return nil, err
	}
	return &ServiceRequirementClassView{inner: bld}, nil
}

func (t *ServiceRequirementClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type SummaryClassView struct {
	inner baml.ClassBuilder
}

func (t *SummaryClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *SummaryClassView) PropertySummary() (ClassPropertyView, error) {
	return t.inner.Property("summary")
}

func (t *TypeBuilder) Summary() (*SummaryClassView, error) {
	bld, err := t.inner.Class("Summary")
	if err != nil {
		return nil, err
	}
	return &SummaryClassView{inner: bld}, nil
}

func (t *SummaryClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type UsageCostClassView struct {
	inner baml.ClassBuilder
}

func (t *UsageCostClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *UsageCostClassView) PropertyUnit() (ClassPropertyView, error) {
	return t.inner.Property("unit")
}

func (t *UsageCostClassView) PropertyCost_per_unit() (ClassPropertyView, error) {
	return t.inner.Property("cost_per_unit")
}

func (t *TypeBuilder) UsageCost() (*UsageCostClassView, error) {
	bld, err := t.inner.Class("UsageCost")
	if err != nil {
		return nil, err
	}
	return &UsageCostClassView{inner: bld}, nil
}

func (t *UsageCostClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}
