// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ go get github.com/boundaryml/baml
//
// ----------------------------------------------------------------------------

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ go install github.com/boundaryml/baml/baml-cli

package types

import (
	"fmt"

	baml "github.com/boundaryml/baml/engine/language_client_go/pkg"
	"github.com/boundaryml/baml/engine/language_client_go/pkg/cffi"
)

type BuildOutput struct {
	Path string `json:"path"`
}

func (c *BuildOutput) Decode(holder *cffi.CFFIValueClass, typeMap baml.TypeMap) {
	typeName := holder.Name
	if typeName.Namespace != cffi.CFFITypeNamespace_TYPES {
		panic(fmt.Sprintf("expected cffi.CFFITypeNamespace_TYPES, got %s", string(typeName.Namespace.String())))
	}
	if typeName.Name != "BuildOutput" {
		panic(fmt.Sprintf("expected BuildOutput, got %s", typeName.Name))
	}

	for _, field := range holder.Fields {
		key := field.Key
		valueHolder := field.Value
		switch key {

		case "path":
			c.Path = baml.Decode(valueHolder).Interface().(string)

		default:

			panic(fmt.Sprintf("unexpected field: %s in class BuildOutput", key))

		}
	}

}

func (c BuildOutput) Encode() (*cffi.CFFIValueHolder, error) {
	fields := map[string]any{}

	fields["path"] = c.Path

	return baml.EncodeClass(c.BamlEncodeName, fields, nil)
}

func (c BuildOutput) BamlTypeName() string {
	return "BuildOutput"
}

func (u BuildOutput) BamlEncodeName() *cffi.CFFITypeName {
	return &cffi.CFFITypeName{
		Namespace: cffi.CFFITypeNamespace_TYPES,
		Name:      "BuildOutput",
	}
}

type BuildOutputCandidate struct {
	Default   string `json:"default"`
	Source    string `json:"source"`
	Framework string `json:"framework"`
	Context   string `json:"context"`
}

func (c *BuildOutputCandidate) Decode(holder *cffi.CFFIValueClass, typeMap baml.TypeMap) {
	typeName := holder.Name
	if typeName.Namespace != cffi.CFFITypeNamespace_TYPES {
		panic(fmt.Sprintf("expected cffi.CFFITypeNamespace_TYPES, got %s", string(typeName.Namespace.String())))
	}
	if typeName.Name != "BuildOutputCandidate" {
		panic(fmt.Sprintf("expected BuildOutputCandidate, got %s", typeName.Name))
	}

	for _, field := range holder.Fields {
		key := field.Key
		valueHolder := field.Value
		switch key {

		case "default":
			c.Default = baml.Decode(valueHolder).Interface().(string)

		case "source":
			c.Source = baml.Decode(valueHolder).Interface().(string)

		case "framework":
			c.Framework = baml.Decode(valueHolder).Interface().(string)

		case "context":
			c.Context = baml.Decode(valueHolder).Interface().(string)

		default:

			panic(fmt.Sprintf("unexpected field: %s in class BuildOutputCandidate", key))

		}
	}

}

func (c BuildOutputCandidate) Encode() (*cffi.CFFIValueHolder, error) {
	fields := map[string]any{}

	fields["default"] = c.Default

	fields["source"] = c.Source

	fields["framework"] = c.Framework

	fields["context"] = c.Context

	return baml.EncodeClass(c.BamlEncodeName, fields, nil)
}

func (c BuildOutputCandidate) BamlTypeName() string {
	return "BuildOutputCandidate"
}

func (u BuildOutputCandidate) BamlEncodeName() *cffi.CFFITypeName {
	return &cffi.CFFITypeName{
		Namespace: cffi.CFFITypeNamespace_TYPES,
		Name:      "BuildOutputCandidate",
	}
}

type CategorizedRoutes struct {
	Routes      []Route `json:"routes"`
	Recommended Route   `json:"recommended"`
}

func (c *CategorizedRoutes) Decode(holder *cffi.CFFIValueClass, typeMap baml.TypeMap) {
	typeName := holder.Name
	if typeName.Namespace != cffi.CFFITypeNamespace_TYPES {
		panic(fmt.Sprintf("expected cffi.CFFITypeNamespace_TYPES, got %s", string(typeName.Namespace.String())))
	}
	if typeName.Name != "CategorizedRoutes" {
		panic(fmt.Sprintf("expected CategorizedRoutes, got %s", typeName.Name))
	}

	for _, field := range holder.Fields {
		key := field.Key
		valueHolder := field.Value
		switch key {

		case "routes":
			c.Routes = baml.Decode(valueHolder).Interface().([]Route)

		case "recommended":
			c.Recommended = baml.Decode(valueHolder).Interface().(Route)

		default:

			panic(fmt.Sprintf("unexpected field: %s in class CategorizedRoutes", key))

		}
	}

}

func (c CategorizedRoutes) Encode() (*cffi.CFFIValueHolder, error) {
	fields := map[string]any{}

	fields["routes"] = c.Routes

	fields["recommended"] = c.Recommended

	return baml.EncodeClass(c.BamlEncodeName, fields, nil)
}

func (c CategorizedRoutes) BamlTypeName() string {
	return "CategorizedRoutes"
}

func (u CategorizedRoutes) BamlEncodeName() *cffi.CFFITypeName {
	return &cffi.CFFITypeName{
		Namespace: cffi.CFFITypeNamespace_TYPES,
		Name:      "CategorizedRoutes",
	}
}

type EnvVarCandidate struct {
	VarName string `json:"varName"`
	File    string `json:"file"`
	Line    int64  `json:"line"`
	Context string `json:"context"`
}

func (c *EnvVarCandidate) Decode(holder *cffi.CFFIValueClass, typeMap baml.TypeMap) {
	typeName := holder.Name
	if typeName.Namespace != cffi.CFFITypeNamespace_TYPES {
		panic(fmt.Sprintf("expected cffi.CFFITypeNamespace_TYPES, got %s", string(typeName.Namespace.String())))
	}
	if typeName.Name != "EnvVarCandidate" {
		panic(fmt.Sprintf("expected EnvVarCandidate, got %s", typeName.Name))
	}

	for _, field := range holder.Fields {
		key := field.Key
		valueHolder := field.Value
		switch key {

		case "varName":
			c.VarName = baml.Decode(valueHolder).Interface().(string)

		case "file":
			c.File = baml.Decode(valueHolder).Interface().(string)

		case "line":
			c.Line = baml.Decode(valueHolder).Interface().(int64)

		case "context":
			c.Context = baml.Decode(valueHolder).Interface().(string)

		default:

			panic(fmt.Sprintf("unexpected field: %s in class EnvVarCandidate", key))

		}
	}

}

func (c EnvVarCandidate) Encode() (*cffi.CFFIValueHolder, error) {
	fields := map[string]any{}

	fields["varName"] = c.VarName

	fields["file"] = c.File

	fields["line"] = c.Line

	fields["context"] = c.Context

	return baml.EncodeClass(c.BamlEncodeName, fields, nil)
}

func (c EnvVarCandidate) BamlTypeName() string {
	return "EnvVarCandidate"
}

func (u EnvVarCandidate) BamlEncodeName() *cffi.CFFITypeName {
	return &cffi.CFFITypeName{
		Namespace: cffi.CFFITypeNamespace_TYPES,
		Name:      "EnvVarCandidate",
	}
}

type EnvVarCategory struct {
	IsDBRelated bool   `json:"isDBRelated"`
	Role        string `json:"role"`
	DbType      string `json:"dbType"`
}

func (c *EnvVarCategory) Decode(holder *cffi.CFFIValueClass, typeMap baml.TypeMap) {
	typeName := holder.Name
	if typeName.Namespace != cffi.CFFITypeNamespace_TYPES {
		panic(fmt.Sprintf("expected cffi.CFFITypeNamespace_TYPES, got %s", string(typeName.Namespace.String())))
	}
	if typeName.Name != "EnvVarCategory" {
		panic(fmt.Sprintf("expected EnvVarCategory, got %s", typeName.Name))
	}

	for _, field := range holder.Fields {
		key := field.Key
		valueHolder := field.Value
		switch key {

		case "isDBRelated":
			c.IsDBRelated = baml.Decode(valueHolder).Interface().(bool)

		case "role":
			c.Role = baml.Decode(valueHolder).Interface().(string)

		case "dbType":
			c.DbType = baml.Decode(valueHolder).Interface().(string)

		default:

			panic(fmt.Sprintf("unexpected field: %s in class EnvVarCategory", key))

		}
	}

}

func (c EnvVarCategory) Encode() (*cffi.CFFIValueHolder, error) {
	fields := map[string]any{}

	fields["isDBRelated"] = c.IsDBRelated

	fields["role"] = c.Role

	fields["dbType"] = c.DbType

	return baml.EncodeClass(c.BamlEncodeName, fields, nil)
}

func (c EnvVarCategory) BamlTypeName() string {
	return "EnvVarCategory"
}

func (u EnvVarCategory) BamlEncodeName() *cffi.CFFITypeName {
	return &cffi.CFFITypeName{
		Namespace: cffi.CFFITypeNamespace_TYPES,
		Name:      "EnvVarCategory",
	}
}

type Error struct {
	Summary      string        `json:"summary"`
	Remediations []Remediation `json:"remediations"`
}

func (c *Error) Decode(holder *cffi.CFFIValueClass, typeMap baml.TypeMap) {
	typeName := holder.Name
	if typeName.Namespace != cffi.CFFITypeNamespace_TYPES {
		panic(fmt.Sprintf("expected cffi.CFFITypeNamespace_TYPES, got %s", string(typeName.Namespace.String())))
	}
	if typeName.Name != "Error" {
		panic(fmt.Sprintf("expected Error, got %s", typeName.Name))
	}

	for _, field := range holder.Fields {
		key := field.Key
		valueHolder := field.Value
		switch key {

		case "summary":
			c.Summary = baml.Decode(valueHolder).Interface().(string)

		case "remediations":
			c.Remediations = baml.Decode(valueHolder).Interface().([]Remediation)

		default:

			panic(fmt.Sprintf("unexpected field: %s in class Error", key))

		}
	}

}

func (c Error) Encode() (*cffi.CFFIValueHolder, error) {
	fields := map[string]any{}

	fields["summary"] = c.Summary

	fields["remediations"] = c.Remediations

	return baml.EncodeClass(c.BamlEncodeName, fields, nil)
}

func (c Error) BamlTypeName() string {
	return "Error"
}

func (u Error) BamlEncodeName() *cffi.CFFITypeName {
	return &cffi.CFFITypeName{
		Namespace: cffi.CFFITypeNamespace_TYPES,
		Name:      "Error",
	}
}

type Intent struct {
	Action   string `json:"action"`
	Platform string `json:"platform"`
	Source   string `json:"source"`
	DryRun   bool   `json:"dryRun"`
}

func (c *Intent) Decode(holder *cffi.CFFIValueClass, typeMap baml.TypeMap) {
	typeName := holder.Name
	if typeName.Namespace != cffi.CFFITypeNamespace_TYPES {
		panic(fmt.Sprintf("expected cffi.CFFITypeNamespace_TYPES, got %s", string(typeName.Namespace.String())))
	}
	if typeName.Name != "Intent" {
		panic(fmt.Sprintf("expected Intent, got %s", typeName.Name))
	}

	for _, field := range holder.Fields {
		key := field.Key
		valueHolder := field.Value
		switch key {

		case "action":
			c.Action = baml.Decode(valueHolder).Interface().(string)

		case "platform":
			c.Platform = baml.Decode(valueHolder).Interface().(string)

		case "source":
			c.Source = baml.Decode(valueHolder).Interface().(string)

		case "dryRun":
			c.DryRun = baml.Decode(valueHolder).Interface().(bool)

		default:

			panic(fmt.Sprintf("unexpected field: %s in class Intent", key))

		}
	}

}

func (c Intent) Encode() (*cffi.CFFIValueHolder, error) {
	fields := map[string]any{}

	fields["action"] = c.Action

	fields["platform"] = c.Platform

	fields["source"] = c.Source

	fields["dryRun"] = c.DryRun

	return baml.EncodeClass(c.BamlEncodeName, fields, nil)
}

func (c Intent) BamlTypeName() string {
	return "Intent"
}

func (u Intent) BamlEncodeName() *cffi.CFFITypeName {
	return &cffi.CFFITypeName{
		Namespace: cffi.CFFITypeNamespace_TYPES,
		Name:      "Intent",
	}
}

type LaunchCommand struct {
	Command string `json:"command"`
}

func (c *LaunchCommand) Decode(holder *cffi.CFFIValueClass, typeMap baml.TypeMap) {
	typeName := holder.Name
	if typeName.Namespace != cffi.CFFITypeNamespace_TYPES {
		panic(fmt.Sprintf("expected cffi.CFFITypeNamespace_TYPES, got %s", string(typeName.Namespace.String())))
	}
	if typeName.Name != "LaunchCommand" {
		panic(fmt.Sprintf("expected LaunchCommand, got %s", typeName.Name))
	}

	for _, field := range holder.Fields {
		key := field.Key
		valueHolder := field.Value
		switch key {

		case "command":
			c.Command = baml.Decode(valueHolder).Interface().(string)

		default:

			panic(fmt.Sprintf("unexpected field: %s in class LaunchCommand", key))

		}
	}

}

func (c LaunchCommand) Encode() (*cffi.CFFIValueHolder, error) {
	fields := map[string]any{}

	fields["command"] = c.Command

	return baml.EncodeClass(c.BamlEncodeName, fields, nil)
}

func (c LaunchCommand) BamlTypeName() string {
	return "LaunchCommand"
}

func (u LaunchCommand) BamlEncodeName() *cffi.CFFITypeName {
	return &cffi.CFFITypeName{
		Namespace: cffi.CFFITypeNamespace_TYPES,
		Name:      "LaunchCommand",
	}
}

type LaunchContext struct {
	Launchers []LauncherFile `json:"launchers"`
	Readme    string         `json:"readme"`
}

func (c *LaunchContext) Decode(holder *cffi.CFFIValueClass, typeMap baml.TypeMap) {
	typeName := holder.Name
	if typeName.Namespace != cffi.CFFITypeNamespace_TYPES {
		panic(fmt.Sprintf("expected cffi.CFFITypeNamespace_TYPES, got %s", string(typeName.Namespace.String())))
	}
	if typeName.Name != "LaunchContext" {
		panic(fmt.Sprintf("expected LaunchContext, got %s", typeName.Name))
	}

	for _, field := range holder.Fields {
		key := field.Key
		valueHolder := field.Value
		switch key {

		case "launchers":
			c.Launchers = baml.Decode(valueHolder).Interface().([]LauncherFile)

		case "readme":
			c.Readme = baml.Decode(valueHolder).Interface().(string)

		default:

			panic(fmt.Sprintf("unexpected field: %s in class LaunchContext", key))

		}
	}

}

func (c LaunchContext) Encode() (*cffi.CFFIValueHolder, error) {
	fields := map[string]any{}

	fields["launchers"] = c.Launchers

	fields["readme"] = c.Readme

	return baml.EncodeClass(c.BamlEncodeName, fields, nil)
}

func (c LaunchContext) BamlTypeName() string {
	return "LaunchContext"
}

func (u LaunchContext) BamlEncodeName() *cffi.CFFITypeName {
	return &cffi.CFFITypeName{
		Namespace: cffi.CFFITypeNamespace_TYPES,
		Name:      "LaunchContext",
	}
}

type LauncherFile struct {
	Name    string `json:"name"`
	Content string `json:"content"`
}

func (c *LauncherFile) Decode(holder *cffi.CFFIValueClass, typeMap baml.TypeMap) {
	typeName := holder.Name
	if typeName.Namespace != cffi.CFFITypeNamespace_TYPES {
		panic(fmt.Sprintf("expected cffi.CFFITypeNamespace_TYPES, got %s", string(typeName.Namespace.String())))
	}
	if typeName.Name != "LauncherFile" {
		panic(fmt.Sprintf("expected LauncherFile, got %s", typeName.Name))
	}

	for _, field := range holder.Fields {
		key := field.Key
		valueHolder := field.Value
		switch key {

		case "name":
			c.Name = baml.Decode(valueHolder).Interface().(string)

		case "content":
			c.Content = baml.Decode(valueHolder).Interface().(string)

		default:

			panic(fmt.Sprintf("unexpected field: %s in class LauncherFile", key))

		}
	}

}

func (c LauncherFile) Encode() (*cffi.CFFIValueHolder, error) {
	fields := map[string]any{}

	fields["name"] = c.Name

	fields["content"] = c.Content

	return baml.EncodeClass(c.BamlEncodeName, fields, nil)
}

func (c LauncherFile) BamlTypeName() string {
	return "LauncherFile"
}

func (u LauncherFile) BamlEncodeName() *cffi.CFFITypeName {
	return &cffi.CFFITypeName{
		Namespace: cffi.CFFITypeNamespace_TYPES,
		Name:      "LauncherFile",
	}
}

type MigrationCommand struct {
	Command     string `json:"command"`
	Confidence  string `json:"confidence"`
	Explanation string `json:"explanation"`
}

func (c *MigrationCommand) Decode(holder *cffi.CFFIValueClass, typeMap baml.TypeMap) {
	typeName := holder.Name
	if typeName.Namespace != cffi.CFFITypeNamespace_TYPES {
		panic(fmt.Sprintf("expected cffi.CFFITypeNamespace_TYPES, got %s", string(typeName.Namespace.String())))
	}
	if typeName.Name != "MigrationCommand" {
		panic(fmt.Sprintf("expected MigrationCommand, got %s", typeName.Name))
	}

	for _, field := range holder.Fields {
		key := field.Key
		valueHolder := field.Value
		switch key {

		case "command":
			c.Command = baml.Decode(valueHolder).Interface().(string)

		case "confidence":
			c.Confidence = baml.Decode(valueHolder).Interface().(string)

		case "explanation":
			c.Explanation = baml.Decode(valueHolder).Interface().(string)

		default:

			panic(fmt.Sprintf("unexpected field: %s in class MigrationCommand", key))

		}
	}

}

func (c MigrationCommand) Encode() (*cffi.CFFIValueHolder, error) {
	fields := map[string]any{}

	fields["command"] = c.Command

	fields["confidence"] = c.Confidence

	fields["explanation"] = c.Explanation

	return baml.EncodeClass(c.BamlEncodeName, fields, nil)
}

func (c MigrationCommand) BamlTypeName() string {
	return "MigrationCommand"
}

func (u MigrationCommand) BamlEncodeName() *cffi.CFFITypeName {
	return &cffi.CFFITypeName{
		Namespace: cffi.CFFITypeNamespace_TYPES,
		Name:      "MigrationCommand",
	}
}

type MigrationContext struct {
	MigrationFiles []MigrationFile `json:"migrationFiles"`
	OrmTools       []string        `json:"ormTools"`
	PackageScripts string          `json:"packageScripts"`
	ConfigSnippets string          `json:"configSnippets"`
}

func (c *MigrationContext) Decode(holder *cffi.CFFIValueClass, typeMap baml.TypeMap) {
	typeName := holder.Name
	if typeName.Namespace != cffi.CFFITypeNamespace_TYPES {
		panic(fmt.Sprintf("expected cffi.CFFITypeNamespace_TYPES, got %s", string(typeName.Namespace.String())))
	}
	if typeName.Name != "MigrationContext" {
		panic(fmt.Sprintf("expected MigrationContext, got %s", typeName.Name))
	}

	for _, field := range holder.Fields {
		key := field.Key
		valueHolder := field.Value
		switch key {

		case "migrationFiles":
			c.MigrationFiles = baml.Decode(valueHolder).Interface().([]MigrationFile)

		case "ormTools":
			c.OrmTools = baml.Decode(valueHolder).Interface().([]string)

		case "packageScripts":
			c.PackageScripts = baml.Decode(valueHolder).Interface().(string)

		case "configSnippets":
			c.ConfigSnippets = baml.Decode(valueHolder).Interface().(string)

		default:

			panic(fmt.Sprintf("unexpected field: %s in class MigrationContext", key))

		}
	}

}

func (c MigrationContext) Encode() (*cffi.CFFIValueHolder, error) {
	fields := map[string]any{}

	fields["migrationFiles"] = c.MigrationFiles

	fields["ormTools"] = c.OrmTools

	fields["packageScripts"] = c.PackageScripts

	fields["configSnippets"] = c.ConfigSnippets

	return baml.EncodeClass(c.BamlEncodeName, fields, nil)
}

func (c MigrationContext) BamlTypeName() string {
	return "MigrationContext"
}

func (u MigrationContext) BamlEncodeName() *cffi.CFFITypeName {
	return &cffi.CFFITypeName{
		Namespace: cffi.CFFITypeNamespace_TYPES,
		Name:      "MigrationContext",
	}
}

type MigrationFile struct {
	Path string `json:"path"`
	Type string `json:"type"`
}

func (c *MigrationFile) Decode(holder *cffi.CFFIValueClass, typeMap baml.TypeMap) {
	typeName := holder.Name
	if typeName.Namespace != cffi.CFFITypeNamespace_TYPES {
		panic(fmt.Sprintf("expected cffi.CFFITypeNamespace_TYPES, got %s", string(typeName.Namespace.String())))
	}
	if typeName.Name != "MigrationFile" {
		panic(fmt.Sprintf("expected MigrationFile, got %s", typeName.Name))
	}

	for _, field := range holder.Fields {
		key := field.Key
		valueHolder := field.Value
		switch key {

		case "path":
			c.Path = baml.Decode(valueHolder).Interface().(string)

		case "type":
			c.Type = baml.Decode(valueHolder).Interface().(string)

		default:

			panic(fmt.Sprintf("unexpected field: %s in class MigrationFile", key))

		}
	}

}

func (c MigrationFile) Encode() (*cffi.CFFIValueHolder, error) {
	fields := map[string]any{}

	fields["path"] = c.Path

	fields["type"] = c.Type

	return baml.EncodeClass(c.BamlEncodeName, fields, nil)
}

func (c MigrationFile) BamlTypeName() string {
	return "MigrationFile"
}

func (u MigrationFile) BamlEncodeName() *cffi.CFFITypeName {
	return &cffi.CFFITypeName{
		Namespace: cffi.CFFITypeNamespace_TYPES,
		Name:      "MigrationFile",
	}
}

type PricingResponse struct {
	Services   []ServicePricing `json:"services"`
	Total_cost float64          `json:"total_cost"`
}

func (c *PricingResponse) Decode(holder *cffi.CFFIValueClass, typeMap baml.TypeMap) {
	typeName := holder.Name
	if typeName.Namespace != cffi.CFFITypeNamespace_TYPES {
		panic(fmt.Sprintf("expected cffi.CFFITypeNamespace_TYPES, got %s", string(typeName.Namespace.String())))
	}
	if typeName.Name != "PricingResponse" {
		panic(fmt.Sprintf("expected PricingResponse, got %s", typeName.Name))
	}

	for _, field := range holder.Fields {
		key := field.Key
		valueHolder := field.Value
		switch key {

		case "services":
			c.Services = baml.Decode(valueHolder).Interface().([]ServicePricing)

		case "total_cost":
			c.Total_cost = baml.Decode(valueHolder).Interface().(float64)

		default:

			panic(fmt.Sprintf("unexpected field: %s in class PricingResponse", key))

		}
	}

}

func (c PricingResponse) Encode() (*cffi.CFFIValueHolder, error) {
	fields := map[string]any{}

	fields["services"] = c.Services

	fields["total_cost"] = c.Total_cost

	return baml.EncodeClass(c.BamlEncodeName, fields, nil)
}

func (c PricingResponse) BamlTypeName() string {
	return "PricingResponse"
}

func (u PricingResponse) BamlEncodeName() *cffi.CFFITypeName {
	return &cffi.CFFITypeName{
		Namespace: cffi.CFFITypeNamespace_TYPES,
		Name:      "PricingResponse",
	}
}

type ProjectSpec struct {
	Name                string               `json:"name"`
	Language            string               `json:"language"`
	ServiceRequirements []ServiceRequirement `json:"serviceRequirements"`
	BuildCommand        string               `json:"buildCommand"`
	StartCommand        string               `json:"startCommand"`
}

func (c *ProjectSpec) Decode(holder *cffi.CFFIValueClass, typeMap baml.TypeMap) {
	typeName := holder.Name
	if typeName.Namespace != cffi.CFFITypeNamespace_TYPES {
		panic(fmt.Sprintf("expected cffi.CFFITypeNamespace_TYPES, got %s", string(typeName.Namespace.String())))
	}
	if typeName.Name != "ProjectSpec" {
		panic(fmt.Sprintf("expected ProjectSpec, got %s", typeName.Name))
	}

	for _, field := range holder.Fields {
		key := field.Key
		valueHolder := field.Value
		switch key {

		case "name":
			c.Name = baml.Decode(valueHolder).Interface().(string)

		case "language":
			c.Language = baml.Decode(valueHolder).Interface().(string)

		case "serviceRequirements":
			c.ServiceRequirements = baml.Decode(valueHolder).Interface().([]ServiceRequirement)

		case "buildCommand":
			c.BuildCommand = baml.Decode(valueHolder).Interface().(string)

		case "startCommand":
			c.StartCommand = baml.Decode(valueHolder).Interface().(string)

		default:

			panic(fmt.Sprintf("unexpected field: %s in class ProjectSpec", key))

		}
	}

}

func (c ProjectSpec) Encode() (*cffi.CFFIValueHolder, error) {
	fields := map[string]any{}

	fields["name"] = c.Name

	fields["language"] = c.Language

	fields["serviceRequirements"] = c.ServiceRequirements

	fields["buildCommand"] = c.BuildCommand

	fields["startCommand"] = c.StartCommand

	return baml.EncodeClass(c.BamlEncodeName, fields, nil)
}

func (c ProjectSpec) BamlTypeName() string {
	return "ProjectSpec"
}

func (u ProjectSpec) BamlEncodeName() *cffi.CFFITypeName {
	return &cffi.CFFITypeName{
		Namespace: cffi.CFFITypeNamespace_TYPES,
		Name:      "ProjectSpec",
	}
}

type Remediation struct {
	Description string `json:"description"`
	CliCommand  string `json:"cliCommand"`
}

func (c *Remediation) Decode(holder *cffi.CFFIValueClass, typeMap baml.TypeMap) {
	typeName := holder.Name
	if typeName.Namespace != cffi.CFFITypeNamespace_TYPES {
		panic(fmt.Sprintf("expected cffi.CFFITypeNamespace_TYPES, got %s", string(typeName.Namespace.String())))
	}
	if typeName.Name != "Remediation" {
		panic(fmt.Sprintf("expected Remediation, got %s", typeName.Name))
	}

	for _, field := range holder.Fields {
		key := field.Key
		valueHolder := field.Value
		switch key {

		case "description":
			c.Description = baml.Decode(valueHolder).Interface().(string)

		case "cliCommand":
			c.CliCommand = baml.Decode(valueHolder).Interface().(string)

		default:

			panic(fmt.Sprintf("unexpected field: %s in class Remediation", key))

		}
	}

}

func (c Remediation) Encode() (*cffi.CFFIValueHolder, error) {
	fields := map[string]any{}

	fields["description"] = c.Description

	fields["cliCommand"] = c.CliCommand

	return baml.EncodeClass(c.BamlEncodeName, fields, nil)
}

func (c Remediation) BamlTypeName() string {
	return "Remediation"
}

func (u Remediation) BamlEncodeName() *cffi.CFFITypeName {
	return &cffi.CFFITypeName{
		Namespace: cffi.CFFITypeNamespace_TYPES,
		Name:      "Remediation",
	}
}

type Route struct {
	Method     string  `json:"method"`
	Path       string  `json:"path"`
	Confidence float64 `json:"confidence"`
}

func (c *Route) Decode(holder *cffi.CFFIValueClass, typeMap baml.TypeMap) {
	typeName := holder.Name
	if typeName.Namespace != cffi.CFFITypeNamespace_TYPES {
		panic(fmt.Sprintf("expected cffi.CFFITypeNamespace_TYPES, got %s", string(typeName.Namespace.String())))
	}
	if typeName.Name != "Route" {
		panic(fmt.Sprintf("expected Route, got %s", typeName.Name))
	}

	for _, field := range holder.Fields {
		key := field.Key
		valueHolder := field.Value
		switch key {

		case "method":
			c.Method = baml.Decode(valueHolder).Interface().(string)

		case "path":
			c.Path = baml.Decode(valueHolder).Interface().(string)

		case "confidence":
			c.Confidence = baml.Decode(valueHolder).Interface().(float64)

		default:

			panic(fmt.Sprintf("unexpected field: %s in class Route", key))

		}
	}

}

func (c Route) Encode() (*cffi.CFFIValueHolder, error) {
	fields := map[string]any{}

	fields["method"] = c.Method

	fields["path"] = c.Path

	fields["confidence"] = c.Confidence

	return baml.EncodeClass(c.BamlEncodeName, fields, nil)
}

func (c Route) BamlTypeName() string {
	return "Route"
}

func (u Route) BamlEncodeName() *cffi.CFFITypeName {
	return &cffi.CFFITypeName{
		Namespace: cffi.CFFITypeNamespace_TYPES,
		Name:      "Route",
	}
}

type RouteCandidate struct {
	Method  string `json:"method"`
	Path    string `json:"path"`
	File    string `json:"file"`
	Line    int64  `json:"line"`
	Context string `json:"context"`
}

func (c *RouteCandidate) Decode(holder *cffi.CFFIValueClass, typeMap baml.TypeMap) {
	typeName := holder.Name
	if typeName.Namespace != cffi.CFFITypeNamespace_TYPES {
		panic(fmt.Sprintf("expected cffi.CFFITypeNamespace_TYPES, got %s", string(typeName.Namespace.String())))
	}
	if typeName.Name != "RouteCandidate" {
		panic(fmt.Sprintf("expected RouteCandidate, got %s", typeName.Name))
	}

	for _, field := range holder.Fields {
		key := field.Key
		valueHolder := field.Value
		switch key {

		case "method":
			c.Method = baml.Decode(valueHolder).Interface().(string)

		case "path":
			c.Path = baml.Decode(valueHolder).Interface().(string)

		case "file":
			c.File = baml.Decode(valueHolder).Interface().(string)

		case "line":
			c.Line = baml.Decode(valueHolder).Interface().(int64)

		case "context":
			c.Context = baml.Decode(valueHolder).Interface().(string)

		default:

			panic(fmt.Sprintf("unexpected field: %s in class RouteCandidate", key))

		}
	}

}

func (c RouteCandidate) Encode() (*cffi.CFFIValueHolder, error) {
	fields := map[string]any{}

	fields["method"] = c.Method

	fields["path"] = c.Path

	fields["file"] = c.File

	fields["line"] = c.Line

	fields["context"] = c.Context

	return baml.EncodeClass(c.BamlEncodeName, fields, nil)
}

func (c RouteCandidate) BamlTypeName() string {
	return "RouteCandidate"
}

func (u RouteCandidate) BamlEncodeName() *cffi.CFFITypeName {
	return &cffi.CFFITypeName{
		Namespace: cffi.CFFITypeNamespace_TYPES,
		Name:      "RouteCandidate",
	}
}

type Service struct {
	Name    string `json:"name"`
	Type    string `json:"type"`
	Plan    string `json:"plan"`
	Storage string `json:"storage"`
}

func (c *Service) Decode(holder *cffi.CFFIValueClass, typeMap baml.TypeMap) {
	typeName := holder.Name
	if typeName.Namespace != cffi.CFFITypeNamespace_TYPES {
		panic(fmt.Sprintf("expected cffi.CFFITypeNamespace_TYPES, got %s", string(typeName.Namespace.String())))
	}
	if typeName.Name != "Service" {
		panic(fmt.Sprintf("expected Service, got %s", typeName.Name))
	}

	for _, field := range holder.Fields {
		key := field.Key
		valueHolder := field.Value
		switch key {

		case "name":
			c.Name = baml.Decode(valueHolder).Interface().(string)

		case "type":
			c.Type = baml.Decode(valueHolder).Interface().(string)

		case "plan":
			c.Plan = baml.Decode(valueHolder).Interface().(string)

		case "storage":
			c.Storage = baml.Decode(valueHolder).Interface().(string)

		default:

			panic(fmt.Sprintf("unexpected field: %s in class Service", key))

		}
	}

}

func (c Service) Encode() (*cffi.CFFIValueHolder, error) {
	fields := map[string]any{}

	fields["name"] = c.Name

	fields["type"] = c.Type

	fields["plan"] = c.Plan

	fields["storage"] = c.Storage

	return baml.EncodeClass(c.BamlEncodeName, fields, nil)
}

func (c Service) BamlTypeName() string {
	return "Service"
}

func (u Service) BamlEncodeName() *cffi.CFFITypeName {
	return &cffi.CFFITypeName{
		Namespace: cffi.CFFITypeNamespace_TYPES,
		Name:      "Service",
	}
}

type ServicePricing struct {
	Service_name string       `json:"service_name"`
	Service_type string       `json:"service_type"`
	Plan         string       `json:"plan"`
	Monthly_cost float64      `json:"monthly_cost"`
	Usage_cost   *[]UsageCost `json:"usage_cost"`
}

func (c *ServicePricing) Decode(holder *cffi.CFFIValueClass, typeMap baml.TypeMap) {
	typeName := holder.Name
	if typeName.Namespace != cffi.CFFITypeNamespace_TYPES {
		panic(fmt.Sprintf("expected cffi.CFFITypeNamespace_TYPES, got %s", string(typeName.Namespace.String())))
	}
	if typeName.Name != "ServicePricing" {
		panic(fmt.Sprintf("expected ServicePricing, got %s", typeName.Name))
	}

	for _, field := range holder.Fields {
		key := field.Key
		valueHolder := field.Value
		switch key {

		case "service_name":
			c.Service_name = baml.Decode(valueHolder).Interface().(string)

		case "service_type":
			c.Service_type = baml.Decode(valueHolder).Interface().(string)

		case "plan":
			c.Plan = baml.Decode(valueHolder).Interface().(string)

		case "monthly_cost":
			c.Monthly_cost = baml.Decode(valueHolder).Interface().(float64)

		case "usage_cost":
			c.Usage_cost = baml.Decode(valueHolder).Interface().(*[]UsageCost)

		default:

			panic(fmt.Sprintf("unexpected field: %s in class ServicePricing", key))

		}
	}

}

func (c ServicePricing) Encode() (*cffi.CFFIValueHolder, error) {
	fields := map[string]any{}

	fields["service_name"] = c.Service_name

	fields["service_type"] = c.Service_type

	fields["plan"] = c.Plan

	fields["monthly_cost"] = c.Monthly_cost

	fields["usage_cost"] = c.Usage_cost

	return baml.EncodeClass(c.BamlEncodeName, fields, nil)
}

func (c ServicePricing) BamlTypeName() string {
	return "ServicePricing"
}

func (u ServicePricing) BamlEncodeName() *cffi.CFFITypeName {
	return &cffi.CFFITypeName{
		Namespace: cffi.CFFITypeNamespace_TYPES,
		Name:      "ServicePricing",
	}
}

type ServiceRequirement struct {
	Type     string `json:"type"`
	Provider string `json:"provider"`
}

func (c *ServiceRequirement) Decode(holder *cffi.CFFIValueClass, typeMap baml.TypeMap) {
	typeName := holder.Name
	if typeName.Namespace != cffi.CFFITypeNamespace_TYPES {
		panic(fmt.Sprintf("expected cffi.CFFITypeNamespace_TYPES, got %s", string(typeName.Namespace.String())))
	}
	if typeName.Name != "ServiceRequirement" {
		panic(fmt.Sprintf("expected ServiceRequirement, got %s", typeName.Name))
	}

	for _, field := range holder.Fields {
		key := field.Key
		valueHolder := field.Value
		switch key {

		case "type":
			c.Type = baml.Decode(valueHolder).Interface().(string)

		case "provider":
			c.Provider = baml.Decode(valueHolder).Interface().(string)

		default:

			panic(fmt.Sprintf("unexpected field: %s in class ServiceRequirement", key))

		}
	}

}

func (c ServiceRequirement) Encode() (*cffi.CFFIValueHolder, error) {
	fields := map[string]any{}

	fields["type"] = c.Type

	fields["provider"] = c.Provider

	return baml.EncodeClass(c.BamlEncodeName, fields, nil)
}

func (c ServiceRequirement) BamlTypeName() string {
	return "ServiceRequirement"
}

func (u ServiceRequirement) BamlEncodeName() *cffi.CFFITypeName {
	return &cffi.CFFITypeName{
		Namespace: cffi.CFFITypeNamespace_TYPES,
		Name:      "ServiceRequirement",
	}
}

type Summary struct {
	Summary string `json:"summary"`
}

func (c *Summary) Decode(holder *cffi.CFFIValueClass, typeMap baml.TypeMap) {
	typeName := holder.Name
	if typeName.Namespace != cffi.CFFITypeNamespace_TYPES {
		panic(fmt.Sprintf("expected cffi.CFFITypeNamespace_TYPES, got %s", string(typeName.Namespace.String())))
	}
	if typeName.Name != "Summary" {
		panic(fmt.Sprintf("expected Summary, got %s", typeName.Name))
	}

	for _, field := range holder.Fields {
		key := field.Key
		valueHolder := field.Value
		switch key {

		case "summary":
			c.Summary = baml.Decode(valueHolder).Interface().(string)

		default:

			panic(fmt.Sprintf("unexpected field: %s in class Summary", key))

		}
	}

}

func (c Summary) Encode() (*cffi.CFFIValueHolder, error) {
	fields := map[string]any{}

	fields["summary"] = c.Summary

	return baml.EncodeClass(c.BamlEncodeName, fields, nil)
}

func (c Summary) BamlTypeName() string {
	return "Summary"
}

func (u Summary) BamlEncodeName() *cffi.CFFITypeName {
	return &cffi.CFFITypeName{
		Namespace: cffi.CFFITypeNamespace_TYPES,
		Name:      "Summary",
	}
}

type UsageCost struct {
	Unit          string  `json:"unit"`
	Cost_per_unit float64 `json:"cost_per_unit"`
}

func (c *UsageCost) Decode(holder *cffi.CFFIValueClass, typeMap baml.TypeMap) {
	typeName := holder.Name
	if typeName.Namespace != cffi.CFFITypeNamespace_TYPES {
		panic(fmt.Sprintf("expected cffi.CFFITypeNamespace_TYPES, got %s", string(typeName.Namespace.String())))
	}
	if typeName.Name != "UsageCost" {
		panic(fmt.Sprintf("expected UsageCost, got %s", typeName.Name))
	}

	for _, field := range holder.Fields {
		key := field.Key
		valueHolder := field.Value
		switch key {

		case "unit":
			c.Unit = baml.Decode(valueHolder).Interface().(string)

		case "cost_per_unit":
			c.Cost_per_unit = baml.Decode(valueHolder).Interface().(float64)

		default:

			panic(fmt.Sprintf("unexpected field: %s in class UsageCost", key))

		}
	}

}

func (c UsageCost) Encode() (*cffi.CFFIValueHolder, error) {
	fields := map[string]any{}

	fields["unit"] = c.Unit

	fields["cost_per_unit"] = c.Cost_per_unit

	return baml.EncodeClass(c.BamlEncodeName, fields, nil)
}

func (c UsageCost) BamlTypeName() string {
	return "UsageCost"
}

func (u UsageCost) BamlEncodeName() *cffi.CFFITypeName {
	return &cffi.CFFITypeName{
		Namespace: cffi.CFFITypeNamespace_TYPES,
		Name:      "UsageCost",
	}
}
