// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ go get github.com/boundaryml/baml
//
// ----------------------------------------------------------------------------

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ go install github.com/boundaryml/baml/baml-cli

package types

import (
	"fmt"

	baml "github.com/boundaryml/baml/engine/language_client_go/pkg"
	"github.com/boundaryml/baml/engine/language_client_go/pkg/cffi"
)

type Intent struct {
	Action   string `json:"action"`
	Platform string `json:"platform"`
}

func (c *Intent) Decode(holder *cffi.CFFIValueClass) {
	typeName := holder.Name
	if typeName.Namespace != cffi.CFFITypeNamespace_TYPES {
		panic(fmt.Sprintf("expected cffi.CFFITypeNamespace_TYPES, got %s", string(typeName.Namespace.String())))
	}
	if typeName.Name != "Intent" {
		panic(fmt.Sprintf("expected Intent, got %s", typeName.Name))
	}

	for _, field := range holder.Fields {
		key := field.Key
		valueHolder := field.Value
		switch key {

		case "action":
			c.Action = baml.Decode(valueHolder).(string)

		case "platform":
			c.Platform = baml.Decode(valueHolder).(string)

		default:
			panic(fmt.Sprintf("unexpected field: %s", key))
		}
	}

}

func (c Intent) Encode() (*cffi.CFFIValueHolder, error) {
	fields := map[string]any{}

	fields["action"] = c.Action

	fields["platform"] = c.Platform

	return baml.EncodeClass(c.BamlEncodeName, fields, nil)
}

func (c Intent) BamlTypeName() string {
	return "Intent"
}

func (u Intent) BamlEncodeName() *cffi.CFFITypeName {
	return &cffi.CFFITypeName{
		Namespace: cffi.CFFITypeNamespace_TYPES,
		Name:      "Intent",
	}
}
